// src/rendering/vulkan/raytracing/denoise/SoRTXRenderBackendRtx.cpp

// NVIDIA RTX denoiser backend ("rtx" slot): the OptiX + CUDA half of the
// denoise concern split out of SoRTXRenderBackendDenoise.cpp.  It owns the
// CUDA context/stream, the OptiX device context and AOV denoiser, the
// CUDA-Vulkan external-memory/semaphore interop that lets the OptiX kernel
// read the path tracer's G-buffers and write the denoised output in place,
// and the embedded PTX normalizer kernel.  All of it is compiled out when
// COIN_BUILD_RTX_DENOISER=0; the declarations in SoRTXRenderBackend.h stay
// present so the dispatch in SoRTXRenderBackendDenoise.cpp links either way.
//
// The OptiX function table definition must live in exactly one TU -- this one.

#include "rendering/vulkan/raytracing/rtx/SoRTXRenderBackend.h"
#include "rendering/vulkan/common/core/SoVulkanConfig.h"
#include "rendering/vulkan/common/core/SoVulkanVma.h"
#include <Inventor/errors/SoDebugError.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <string>
#include <thread>
#include <rendering/vulkan/raytracing/rtx/SoRTXRenderBackendP.h>

#include "vk_mem_alloc.h"
#if COIN_BUILD_RTX_DENOISER
// The OptiX function table lives in exactly this TU.
#include <optix_function_table_definition.h>
#include <thread>
#include <vector>
#include <cstdio>
#include <cerrno>
#include <fcntl.h>
#include <unistd.h>
#endif

using namespace SoRTXBackend;

#if COIN_BUILD_RTX_DENOISER
// PTX for the sum->average normalizer (compiled with nvcc -ptx -arch=sm_75).
// Converts an accumulated radiance sum (rgb) / sample-count (w) buffer into
// the average color (and sets w = 1 for valid pixels, 0 for empty ones) that
// the OptiX AOV denoiser expects as its AOV beauty input.
namespace fca_rtx {
const char * kCointerpNormalizePtx =
"//\n"
"// Generated by NVIDIA NVVM Compiler\n"
"//\n"
"// Compiler Build ID: CL-38244171\n"
"// Cuda compilation tools, release 13.3, V13.3.73\n"
"// Based on NVVM 23.0.0\n"
"//\n"
"\n"
".version 9.3\n"
".target sm_75\n"
".address_size 64\n"
"\n"
"	// .globl	cointerp_normalize\n"
"\n"
".visible .entry cointerp_normalize(\n"
"	.param .u64 .ptr .align 1 cointerp_normalize_param_0,\n"
"	.param .u32 cointerp_normalize_param_1\n"
")\n"
"{\n"
"	.reg .pred 	%p<4>;\n"
"	.reg .b32 	%r<16>;\n"
"	.reg .b64 	%rd<5>;\n"
"\n"
"	ld.param.b64 	%rd2, [cointerp_normalize_param_0];\n"
"	ld.param.b32 	%r3, [cointerp_normalize_param_1];\n"
"	mov.u32 	%r4, %ctaid.x;\n"
"	mov.u32 	%r5, %ntid.x;\n"
"	mov.u32 	%r6, %tid.x;\n"
"	mad.lo.s32 	%r1, %r4, %r5, %r6;\n"
"	setp.ge.s32 	%p1, %r1, %r3;\n"
"	@%p1 bra 	$L__BB0_4;\n"
"	cvta.to.global.u64 	%rd3, %rd2;\n"
"	mul.wide.s32 	%rd4, %r1, 16;\n"
"	add.s64 	%rd1, %rd3, %rd4;\n"
"	ld.global.b32 	%r7, [%rd1+12];\n"
"	abs.f32 	%r8, %r7;\n"
"	setp.gt.f32 	%p2, %r8, 0f3727C5AC;\n"
"	selp.f32 	%r2, %r7, 0f00000000, %p2;\n"
"	setp.leu.f32 	%p3, %r2, 0f00000000;\n"
"	@%p3 bra 	$L__BB0_3;\n"
"	.pragma \"used_bytes_mask 0xfff\";\n"
"	ld.global.v4.b32 	{%r9, %r10, %r11, %r12}, [%rd1];\n"
"	div.rn.f32 	%r13, %r9, %r2;\n"
"	div.rn.f32 	%r14, %r10, %r2;\n"
"	div.rn.f32 	%r15, %r11, %r2;\n"
"	st.global.v4.b32 	[%rd1], {%r13, %r14, %r15, 0f3F800000};\n"
"	bra.uni 	$L__BB0_4;\n"
"$L__BB0_3:\n"
"	st.global.b32 	[%rd1+12], 0;\n"
"$L__BB0_4:\n"
"	ret;\n"
"\n"
"}\n";
} // namespace fca_rtx
using fca_rtx::kCointerpNormalizePtx;
#endif // COIN_BUILD_RTX_DENOISER

void
SoRTXRenderBackend::teardownRtxDenoiser()
{
#if COIN_BUILD_RTX_DENOISER
  // Report a CUDA/OptiX teardown failure (both use 0 for success) without
  // aborting the remaining cleanup.
  auto reportTeardown = [this](const char * what, int res) {
    if (res == 0) return;
    char msg[192];
    std::snprintf(msg, sizeof(msg),
                  "RTX denoiser teardown: %s failed (result %d)", what, res);
    this->emitError(msg);
  };
  // CUDA driver memory operations act on the current context, so make ours
  // current before freeing the denoiser-owned allocations.
  if (this->rtxCudaCtx) {
    reportTeardown("cuCtxSetCurrent",
                   static_cast<int>(cuCtxSetCurrent(this->rtxCudaCtx)));
  }
  if (this->rtxStream) {
    reportTeardown("cuStreamSynchronize",
                   static_cast<int>(cuStreamSynchronize(this->rtxStream)));
  }
  if (this->rtxInteropSemaphoresReady || this->rtxVkToCudaSem != VK_NULL_HANDLE ||
      this->rtxCudaToVkSem != VK_NULL_HANDLE ||
      this->rtxVkToCudaCudaSem != nullptr ||
      this->rtxCudaToVkCudaSem != nullptr) {
    this->destroyRtxInteropSemaphore(this->rtxVkToCudaSem,
                                     this->rtxVkToCudaCudaSem, true);
    this->destroyRtxInteropSemaphore(this->rtxCudaToVkSem,
                                     this->rtxCudaToVkCudaSem, true);
  }
  this->rtxInteropSemaphoresReady = false;
  this->rtxVkToCudaSignalPending = false;
  this->rtxCudaSignalPending = false;
  if (this->rtxDenoiser) {
    reportTeardown("optixDenoiserDestroy",
                   static_cast<int>(optixDenoiserDestroy(this->rtxDenoiser)));
    this->rtxDenoiser = nullptr;
  }
  if (this->rtxDeviceContext) {
    reportTeardown(
      "optixDeviceContextDestroy",
      static_cast<int>(optixDeviceContextDestroy(this->rtxDeviceContext)));
    this->rtxDeviceContext = nullptr;
  }
  if (this->rtxNormModule) {
    reportTeardown("cuModuleUnload",
                   static_cast<int>(cuModuleUnload(this->rtxNormModule)));
    this->rtxNormModule = nullptr;
    this->rtxNormKernel = nullptr;
  }
  if (this->rtxIntensity) { cuMemFree(this->rtxIntensity); this->rtxIntensity = 0; }
  if (this->rtxState) { cuMemFree(this->rtxState); this->rtxState = 0; }
  if (this->rtxScratch) { cuMemFree(this->rtxScratch); this->rtxScratch = 0; }

  // The four working images were exported from Vulkan and imported into CUDA.
  // Reverse the import (release the CUDA alias) BEFORE freeing the Vulkan
  // allocation that owns the memory.
  auto releaseInterop = [this, &reportTeardown](VkBuffer & buf, VmaAllocation & mem,
                               CUexternalMemory & ext) {
    if (ext) {
      reportTeardown("cuDestroyExternalMemory",
                     static_cast<int>(cuDestroyExternalMemory(ext)));
      ext = nullptr;
    }
    const VkBuffer vkBuf = buf;
    const VmaAllocation vkMem = mem;
    buf = VK_NULL_HANDLE;
    mem = VK_NULL_HANDLE;
    if (vkBuf != VK_NULL_HANDLE || vkMem != VK_NULL_HANDLE) {
      this->deferDestroy([this, vkBuf, vkMem]() {
        vmaDestroyBuffer(this->vmaAllocator, vkBuf, vkMem);
      });
    }
  };
  releaseInterop(this->rtxColorVk, this->rtxColorMem, this->rtxColorExt);
  releaseInterop(this->rtxAlbedoVk, this->rtxAlbedoMem, this->rtxAlbedoExt);
  releaseInterop(this->rtxNormalVk, this->rtxNormalMem, this->rtxNormalExt);
  releaseInterop(this->rtxMotionVk, this->rtxMotionMem, this->rtxMotionExt);
  releaseInterop(this->rtxOutputVk, this->rtxOutputMem, this->rtxOutputExt);
  this->rtxColorImage = 0;
  this->rtxAlbedoImage = 0;
  this->rtxNormalImage = 0;
  this->rtxMotionImage = 0;
  this->rtxOutputImage = 0;
  this->rtxInteropReady = false;

  if (this->rtxStream) {
    reportTeardown("cuStreamDestroy",
                   static_cast<int>(cuStreamDestroy(this->rtxStream)));
    this->rtxStream = nullptr;
  }
  if (this->rtxCudaCtx) {
    reportTeardown("cuCtxDestroy",
                   static_cast<int>(cuCtxDestroy(this->rtxCudaCtx)));
    this->rtxCudaCtx = nullptr;
  }
#endif
}

#if COIN_BUILD_RTX_DENOISER
namespace {

void
rtxLogCallback(unsigned int level, const char * tag, const char * message,
               void * /*cbdata*/)
{
  if (SoVulkanConfig::get().rtxDebug.denoiserDebug || level <= 2) {
    fprintf(stderr, "[RTX-DENOISER] level=%u tag=%s: %s\n", level,
            tag ? tag : "", message ? message : "");
  }
}

} // namespace

bool
SoRTXRenderBackend::initRtxCuda()
{
  if (this->rtxDeviceContext) return true;
  if (this->rtxCudaInitFailed) return false;

  // Initialize CUDA driver once per process.
  if (cuInit(0) != CUDA_SUCCESS) {
    this->emitError("RTX denoiser: cuInit failed");
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Enumerate devices and pick the CUDA device that corresponds to the Vulkan
  // physical device, so the external-memory interop imports memory from the
  // same GPU.  Without a match (no UUID available, or the device is absent
  // from this CUDA context) fall back to the first Turing-or-newer device --
  // the OptiX AOV denoiser needs compute capability 7.5+ (Turing) and a
  // single-slot context.  Picking device 0 unconditionally was safe only on a
  // single-GPU NVIDIA machine; on a dual-NVIDIA workstation it could bind CUDA
  // to a different GPU than the one rendering, silently corrupting the interop.
  int deviceCount = 0;
  if (cuDeviceGetCount(&deviceCount) != CUDA_SUCCESS || deviceCount <= 0) {
    this->emitError(
      "RTX denoiser: cuDeviceGetCount failed or returned no CUDA devices");
    this->rtxCudaInitFailed = true;
    return false;
  }

  int chosenIndex = -1;
  int fallbackIndex = -1;
  for (int i = 0; i < deviceCount; ++i) {
    CUdevice dev {};
    if (cuDeviceGet(&dev, i) != CUDA_SUCCESS) continue;
    int ccMajor = 0, ccMinor = 0;
    if (cuDeviceGetAttribute(
          &ccMajor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR,
          dev) != CUDA_SUCCESS ||
        cuDeviceGetAttribute(
          &ccMinor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR,
          dev) != CUDA_SUCCESS) {
      // Cannot judge this device's capability; skip it rather than assuming.
      continue;
    }
    // Turing (7.5) is the minimum for the RTX/OptiX denoiser here; older
    // devices (Maxwell/Kepler) cannot run the AOV denoiser.
    if (ccMajor < 7 || (ccMajor == 7 && ccMinor < 5)) continue;
    if (fallbackIndex < 0) fallbackIndex = i;
    // Prefer the device whose UUID matches the Vulkan physical device.
    if (this->haveDeviceUUID) {
      CUuuid cuUuid {};
      if (cuDeviceGetUuid(&cuUuid, dev) == CUDA_SUCCESS) {
        if (std::memcmp(cuUuid.bytes, this->deviceUUID, sizeof(this->deviceUUID))
            == 0) {
          chosenIndex = i;
          break;
        }
      }
    }
  }
  if (chosenIndex < 0 && this->haveDeviceUUID) {
    // A UUID was available, but none of the CUDA devices matched it.  Do not
    // silently fall back to another GPU: importing memory into a different
    // CUDA context would bind the denoiser to the wrong physical device.
    if (SoVulkanConfig::get().rtxDebug.denoiserDebug) {
      fprintf(stderr,
              "[RTX-DENOISER] no CUDA device matches the Vulkan device UUID "
              "(count=%d)\n",
              deviceCount);
    }
    this->emitError(
      "RTX denoiser: no CUDA device matches the Vulkan device UUID");
    this->rtxCudaInitFailed = true;
    return false;
  }
  if (chosenIndex < 0) chosenIndex = fallbackIndex;
  if (chosenIndex < 0) {
    this->emitError(
      "RTX denoiser: no Turing-or-newer CUDA device (compute capability 7.5 "
      "required)");
    this->rtxCudaInitFailed = true;
    return false;
  }
  if (cuDeviceGet(&this->rtxCudaDevice, chosenIndex) != CUDA_SUCCESS) {
    this->emitError("RTX denoiser: cuDeviceGet failed for the chosen device");
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Create a private CUDA context (never the current one) for the denoiser.
  // CUDA 13.x maps cuCtxCreate to cuCtxCreate_v4, which takes a
  // CUctxCreateParams* and a flags/device triple.
  if (cuCtxCreate(&this->rtxCudaCtx, nullptr, CU_CTX_SCHED_BLOCKING_SYNC,
                  this->rtxCudaDevice) != CUDA_SUCCESS) {
    this->emitError("RTX denoiser: cuCtxCreate failed");
    this->rtxCudaInitFailed = true;
    return false;
  }

  // One stream shared by the normalize kernel, optixDenoiserComputeIntensity
  // and optixDenoiserInvoke.  Keeping them on a single stream (as NVIDIA's
  // nvpro vk_optix_denoise example does) orders the hdrIntensity write before
  // the invoke reads it.
  if (cuStreamCreate(&this->rtxStream, 0) != CUDA_SUCCESS) {
    this->emitError("RTX denoiser: cuStreamCreate failed");
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Bind the context for the OptiX device-context creation call.
  if (cuCtxSetCurrent(this->rtxCudaCtx) != CUDA_SUCCESS) {
    this->emitError("RTX denoiser: cuCtxSetCurrent failed");
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Initialize the OptiX host-side function table (dlopens libnvoptix.so.1).
  if (optixInit() != OPTIX_SUCCESS) {
    this->emitError(
      "RTX denoiser: optixInit failed (libnvoptix.so.1 unavailable)");
    this->rtxCudaInitFailed = true;
    return false;
  }

  OptixDeviceContextOptions options {};
  options.logCallbackFunction = rtxLogCallback;
  options.logCallbackLevel = 2; // errors only
  if (optixDeviceContextCreate(this->rtxCudaCtx, &options,
                               &this->rtxDeviceContext) != OPTIX_SUCCESS) {
    this->emitError("RTX denoiser: optixDeviceContextCreate failed");
    this->rtxCudaInitFailed = true;
    return false;
  }
  return true;
}

bool
SoRTXRenderBackend::initRtxDenoiser()
{
  if (this->rtxDenoiser) return true;
  if (!this->rtxDeviceContext) return false;

  OptixDenoiserOptions dopt {};
  // AOV model with albedo + normal guides: standard for path-traced beauty.
  dopt.guideAlbedo = 1;
  dopt.guideNormal = 1;
  dopt.denoiseAlpha = OPTIX_DENOISER_ALPHA_MODE_COPY;
  if (optixDenoiserCreate(this->rtxDeviceContext, this->rtxModelKind, &dopt,
                          &this->rtxDenoiser) != OPTIX_SUCCESS) {
    return false;
  }
  if (optixDenoiserComputeMemoryResources(this->rtxDenoiser,
                                          this->denoiseWidth,
                                          this->denoiseHeight,
                                          &this->rtxSizes) != OPTIX_SUCCESS) {
    return false;
  }

  this->rtxImagePitch =
    static_cast<uint64_t>(this->denoiseWidth) * 4 * sizeof(float);
  this->rtxOutputPitchBytes = static_cast<size_t>(this->rtxImagePitch);
  this->rtxStateBytes = this->rtxSizes.stateSizeInBytes;

  // Scratch must cover the max of the set-up/invoke scratch (without overlap)
  // and the overlap-allow scratch, whichever the driver needs.
  this->rtxScratchBytes =
    std::max(this->rtxSizes.withoutOverlapScratchSizeInBytes,
             this->rtxSizes.withOverlapScratchSizeInBytes);

  const size_t imageBytes = this->rtxOutputPitchBytes * this->denoiseHeight;
  if (cuMemAlloc(&this->rtxScratch, this->rtxScratchBytes) != CUDA_SUCCESS) {
    return false;
  }
  if (cuMemAlloc(&this->rtxState, this->rtxStateBytes) != CUDA_SUCCESS) {
    return false;
  }
  if (cuMemAlloc(&this->rtxIntensity, sizeof(float)) != CUDA_SUCCESS) {
    return false;
  }

  // The four working images are exportable device-local Vulkan buffers
  // imported into CUDA, so OptiX (and the normalize kernel) read/write them
  // directly on the GPU with no host staging in between.
  VkBufferUsageFlags inUsage =
    VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT |
    VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
  VkBufferUsageFlags outUsage =
    VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
    VK_BUFFER_USAGE_TRANSFER_DST_BIT;
  if (!this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxColorVk,
                                    this->rtxColorMem, this->rtxColorExt,
                                    this->rtxColorImage) ||
      !this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxAlbedoVk,
                                    this->rtxAlbedoMem, this->rtxAlbedoExt,
                                    this->rtxAlbedoImage) ||
      !this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxNormalVk,
                                    this->rtxNormalMem, this->rtxNormalExt,
                                    this->rtxNormalImage) ||
      !this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxMotionVk,
                                    this->rtxMotionMem, this->rtxMotionExt,
                                    this->rtxMotionImage) ||
      !this->createRtxInteropBuffer(imageBytes, outUsage, this->rtxOutputVk,
                                    this->rtxOutputMem, this->rtxOutputExt,
                                    this->rtxOutputImage)) {
    this->emitError("RTX denoiser: failed to create CUDA-Vulkan interop buffers");
    return false;
  }

  // Load the sum->average normalize kernel (PTX embedded below).  It runs in
  // the ongoing denoiser stream over the color image.
  if (cuModuleLoadData(&this->rtxNormModule, kCointerpNormalizePtx) !=
        CUDA_SUCCESS ||
      cuModuleGetFunction(&this->rtxNormKernel, this->rtxNormModule,
                          "cointerp_normalize") != CUDA_SUCCESS) {
    this->emitError("RTX denoiser: failed to load normalize kernel");
    return false;
  }

  this->ensureRtxInteropSemaphores();
  this->rtxInteropReady = true;
  return true;
}

bool
SoRTXRenderBackend::createRtxInteropBuffer(size_t bytes,
                                           VkBufferUsageFlags usage,
                                           VkBuffer & buffer,
                                           VmaAllocation & memory,
                                           CUexternalMemory & ext,
                                           CUdeviceptr & devPtr)
{
  if (!this->vkGetMemoryFdKHR) {
    this->vkGetMemoryFdKHR = loadDispatch<PFN_vkGetMemoryFdKHR>(
      vkGetDeviceProcAddr(this->device, "vkGetMemoryFdKHR"));
    if (!this->vkGetMemoryFdKHR) {
      this->emitError("RTX denoiser: vkGetMemoryFdKHR unavailable; the "
                      "VK_KHR_external_memory_fd hint was not enabled on "
                      "the device");
      return false;
    }
  }

  VkExternalMemoryBufferCreateInfo externalBufInfo {};
  externalBufInfo.sType = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO;
  externalBufInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
  VkBufferCreateInfo ci {};
  ci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  ci.pNext = &externalBufInfo;
  ci.size = bytes;
  ci.usage = usage;
  ci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

  // Exportability depends only on the buffer's usage, so query it before
  // touching the allocator.
  VkPhysicalDeviceExternalBufferInfo externalQuery {};
  externalQuery.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO;
  externalQuery.flags = 0;
  externalQuery.usage = usage;
  externalQuery.handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
  VkExternalBufferProperties externalProps {};
  externalProps.sType = VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES;
  vkGetPhysicalDeviceExternalBufferProperties(this->physicalDevice,
                                              &externalQuery, &externalProps);
  const VkExternalMemoryProperties & externalMem =
    externalProps.externalMemoryProperties;
  const bool exportable =
    (externalMem.externalMemoryFeatures &
     VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT) != 0;
  const bool compatibleOpaque =
    (externalMem.compatibleHandleTypes &
     VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT) != 0;
  if (!exportable || !compatibleOpaque) {
    if (SoVulkanConfig::get().rtxDebug.denoiserDebug) {
      fprintf(stderr,
              "[RTX-DENOISER] CUDA external buffer is not exportable: "
              "features=0x%x compatible=0x%x usage=0x%x bytes=%zu\n",
              static_cast<unsigned>(externalMem.externalMemoryFeatures),
              static_cast<unsigned>(externalMem.compatibleHandleTypes),
              static_cast<unsigned>(usage), bytes);
    }
    return false;
  }

  // Lazily create the custom export pool.  The five interop buffers share one
  // device-local memory type; the pool exists solely to carry
  // VkExportMemoryAllocateInfo into every allocation's pNext chain, which is
  // the only way VMA can export an opaque FD (VkMemoryAllocateInfo has no
  // direct field for it).  rtxInteropExportInfo must outlive the pool: VMA
  // stores the pointer, not a copy.
  if (this->rtxInteropPool == VK_NULL_HANDLE) {
    // Resolve the pool's memory type from the buffer's own requirements.
    // vmaFindMemoryTypeIndexForBufferInfo() is the obvious call, but it takes
    // VMA's Vulkan-1.3 vkGetDeviceBufferMemoryRequirements path whenever the
    // allocator's apiVersion is >= 1.3, and this app never enables the
    // maintenance4 feature that entry point requires; with a layer in the
    // chain that resolves to a null driver entry and crashes.  Query the 1.0
    // requirements of a throw-away buffer instead (no memory is bound to it).
    VkBuffer probe = VK_NULL_HANDLE;
    if (vkCreateBuffer(this->device, &ci, this->allocator, &probe) !=
        VK_SUCCESS) {
      this->emitError("RTX denoiser: failed to create the CUDA interop "
                      "memory-type probe buffer");
      return false;
    }
    VkMemoryRequirements req {};
    vkGetBufferMemoryRequirements(this->device, probe, &req);
    vkDestroyBuffer(this->device, probe, this->allocator);
    uint32_t memTypeIndex = 0;
    if (!this->memProps.pick(req, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
                             memTypeIndex)) {
      this->emitError("RTX denoiser: no memory type for the exportable "
                      "CUDA interop buffers");
      return false;
    }
    this->rtxInteropExportInfo.sType =
      VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO;
    this->rtxInteropExportInfo.pNext = nullptr;
    this->rtxInteropExportInfo.handleTypes =
      VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
    VmaPoolCreateInfo poolInfo {};
    poolInfo.memoryTypeIndex = memTypeIndex;
    poolInfo.pMemoryAllocateNext =
      static_cast<void *>(&this->rtxInteropExportInfo);
    if (vmaCreatePool(this->vmaAllocator, &poolInfo,
                      &this->rtxInteropPool) != VK_SUCCESS) {
      this->rtxInteropPool = VK_NULL_HANDLE;
      this->emitError("RTX denoiser: vmaCreatePool for the CUDA interop "
                      "buffers failed");
      return false;
    }
  }

  // A dedicated allocation gives each interop buffer its own VkDeviceMemory at
  // offset 0: the FD export is per memory object and CUDA imports it whole, so
  // suballocating several buffers out of one block would alias them.
  SoVulkanShared::VmaBufferDesc desc;
  desc.size = bytes;
  desc.usage = usage;
  desc.pNext = &externalBufInfo;
  desc.flags = VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT;
  desc.pool = this->rtxInteropPool;
  VmaAllocationInfo allocationInfo {};
  const SoVulkan::Result create = SoVulkanShared::createVmaBuffer(
    this->vmaAllocator, desc, "createRtxInteropBuffer", buffer, memory,
    &allocationInfo);
  if (!create.isOk()) {
    if (SoVulkanConfig::get().rtxDebug.denoiserDebug) {
      fprintf(stderr,
              "[RTX-DENOISER] failed to allocate external CUDA/Vulkan "
              "buffer: bytes=%zu\n", bytes);
    }
    this->emitError(create.message().c_str());
    buffer = VK_NULL_HANDLE;
    memory = VK_NULL_HANDLE;
    return false;
  }
  // vkGetMemoryFdKHR takes the raw VkDeviceMemory; VMA exposes it through the
  // allocation info.  The allocation is dedicated, so its size is the whole
  // memory object and the buffer sits at offset 0.
  const VkDeviceMemory vkMemory = allocationInfo.deviceMemory;
  const VkDeviceSize importSize =
    allocationInfo.size != 0 ? allocationInfo.size : bytes;

  // Export an opaque FD and hand it to CUDA to map as a device pointer.
  VkMemoryGetFdInfoKHR fdInfo {};
  fdInfo.sType = VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR;
  fdInfo.memory = vkMemory;
  fdInfo.handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
  int fd = -1;
  const VkResult fdRes = this->vkGetMemoryFdKHR(this->device, &fdInfo, &fd);
  if (fdRes != VK_SUCCESS || fd < 0) {
    if (fdRes != VK_SUCCESS) {
      this->emitError(("createRtxInteropBuffer: vkGetMemoryFdKHR failed: "
                       + SoVulkanShared::vkResultName(fdRes)).c_str());
    }
    else {
      this->emitError(
        "createRtxInteropBuffer: vkGetMemoryFdKHR returned an invalid fd");
    }
    vmaDestroyBuffer(this->vmaAllocator, buffer, memory);
    buffer = VK_NULL_HANDLE;
    memory = VK_NULL_HANDLE;
    return false;
  }

  CUDA_EXTERNAL_MEMORY_HANDLE_DESC hdesc {};
  hdesc.type = CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD;
  hdesc.handle.fd = fd;
  hdesc.size = importSize;
  CUresult cuRes = cuImportExternalMemory(&ext, &hdesc);
  if (cuRes != CUDA_SUCCESS) {
    this->emitError("createRtxInteropBuffer: cuImportExternalMemory failed");
    ::close(fd);
    vmaDestroyBuffer(this->vmaAllocator, buffer, memory);
    buffer = VK_NULL_HANDLE;
    memory = VK_NULL_HANDLE;
    ext = nullptr;
    return false;
  }
  ::close(fd); // CUDA retains a dup of the FD.

  CUDA_EXTERNAL_MEMORY_BUFFER_DESC bdesc {};
  bdesc.offset = 0;
  bdesc.size = importSize;
  bdesc.flags = 0;
  cuRes = cuExternalMemoryGetMappedBuffer(&devPtr, ext, &bdesc);
  if (cuRes != CUDA_SUCCESS) {
    this->emitError(
      "createRtxInteropBuffer: cuExternalMemoryGetMappedBuffer failed");
    const CUresult cleanupRes = cuDestroyExternalMemory(ext);
    if (cleanupRes != CUDA_SUCCESS) {
      this->emitError("createRtxInteropBuffer: cuDestroyExternalMemory "
                      "(cleanup) failed");
    }
    ext = nullptr;
    vmaDestroyBuffer(this->vmaAllocator, buffer, memory);
    buffer = VK_NULL_HANDLE;
    memory = VK_NULL_HANDLE;
    return false;
  }
  return true;
}

bool
SoRTXRenderBackend::createRtxInteropSemaphore(VkSemaphore & vkSem,
                                              CUexternalSemaphore & cudaSem)
{
  vkSem = VK_NULL_HANDLE;
  cudaSem = nullptr;
  if (!this->device) {
    return false;
  }
  if (!this->vkGetSemaphoreFdKHR) {
    this->vkGetSemaphoreFdKHR = loadDispatch<PFN_vkGetSemaphoreFdKHR>(
      vkGetDeviceProcAddr(this->device, "vkGetSemaphoreFdKHR"));
    if (!this->vkGetSemaphoreFdKHR) {
      return false;
    }
  }

  VkExportSemaphoreCreateInfo exportInfo {};
  exportInfo.sType = VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO;
  exportInfo.handleTypes = VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT;
  VkSemaphoreCreateInfo ci {};
  ci.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
  ci.pNext = &exportInfo;
  ci.flags = 0;
  if (vkCreateSemaphore(this->device, &ci, this->allocator, &vkSem) !=
      VK_SUCCESS) {
    return false;
  }

  VkSemaphoreGetFdInfoKHR fdInfo {};
  fdInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_GET_FD_INFO_KHR;
  fdInfo.semaphore = vkSem;
  fdInfo.handleType = VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT;
  int fd = -1;
  if (this->vkGetSemaphoreFdKHR(this->device, &fdInfo, &fd) != VK_SUCCESS ||
      fd < 0) {
    vkDestroySemaphore(this->device, vkSem, this->allocator);
    vkSem = VK_NULL_HANDLE;
    return false;
  }

  CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC hd {};
  hd.type = CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD;
  hd.handle.fd = fd;
  hd.flags = 0;
  const CUresult cr = cuImportExternalSemaphore(&cudaSem, &hd);
  ::close(fd);
  if (cr != CUDA_SUCCESS) {
    vkDestroySemaphore(this->device, vkSem, this->allocator);
    vkSem = VK_NULL_HANDLE;
    cudaSem = nullptr;
    return false;
  }
  return true;
}

void
SoRTXRenderBackend::destroyRtxInteropSemaphore(VkSemaphore & vkSem,
                                               CUexternalSemaphore & cudaSem,
                                               bool deferVulkan)
{
  if (cudaSem) {
    const CUresult destroyRes = cuDestroyExternalSemaphore(cudaSem);
    if (destroyRes != CUDA_SUCCESS) {
      char msg[160];
      std::snprintf(msg, sizeof(msg),
                    "destroyRtxInteropSemaphore: cuDestroyExternalSemaphore "
                    "failed (CUDA result %d)", static_cast<int>(destroyRes));
      this->emitError(msg);
    }
    cudaSem = nullptr;
  }
  if (vkSem != VK_NULL_HANDLE) {
    const VkSemaphore sem = vkSem;
    vkSem = VK_NULL_HANDLE;
    if (deferVulkan) {
      this->deferDestroy([this, sem]() {
        if (sem != VK_NULL_HANDLE) {
          vkDestroySemaphore(this->device, sem, this->allocator);
        }
      });
    }
    else if (this->device != VK_NULL_HANDLE) {
      vkDestroySemaphore(this->device, sem, this->allocator);
    }
  }
}

void
SoRTXRenderBackend::ensureRtxInteropSemaphores()
{
  if (this->rtxInteropSemaphoresReady) {
    return;
  }
  if (!this->rtxCudaCtx) {
    return;
  }
  if (cuCtxSetCurrent(this->rtxCudaCtx) != CUDA_SUCCESS) {
    return;
  }

  bool ok = false;
  if (this->createRtxInteropSemaphore(this->rtxVkToCudaSem,
                                      this->rtxVkToCudaCudaSem) &&
      this->createRtxInteropSemaphore(this->rtxCudaToVkSem,
                                      this->rtxCudaToVkCudaSem)) {
    this->rtxInteropSemaphoresReady = true;
    ok = true;
  }
  if (!ok) {
    this->destroyRtxInteropSemaphore(this->rtxVkToCudaSem,
                                     this->rtxVkToCudaCudaSem, false);
    this->destroyRtxInteropSemaphore(this->rtxCudaToVkSem,
                                     this->rtxCudaToVkCudaSem, false);
    this->rtxInteropSemaphoresReady = false;
  }
  this->rtxVkToCudaSignalPending = false;
  this->rtxCudaSignalPending = false;
  if (SoVulkanConfig::get().rtxDebug.denoiserDebug) {
    fprintf(stderr, "[RTX-DENOISER] CUDA/Vulkan semaphores ready=%s\n",
            ok ? "yes" : "no");
  }
}

static bool
submitRtxSemaphoreBarrier(VkDevice device, VkCommandPool pool, VkQueue queue,
                          const VkAllocationCallbacks * allocator,
                          VkSemaphore semaphore, bool isSignal)
{
  (void)allocator;
  if (device == VK_NULL_HANDLE || pool == VK_NULL_HANDLE ||
      queue == VK_NULL_HANDLE || semaphore == VK_NULL_HANDLE) {
    return false;
  }

  VkCommandBufferAllocateInfo ai {};
  ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  ai.commandPool = pool;
  ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  ai.commandBufferCount = 1;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  if (vkAllocateCommandBuffers(device, &ai, &cmd) != VK_SUCCESS) {
    return false;
  }

  VkCommandBufferBeginInfo bi {};
  bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
  bool ok = vkBeginCommandBuffer(cmd, &bi) == VK_SUCCESS;
  if (ok) {
    SoVulkanShared::memoryBarrier(
      cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
      VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, 0, 0);
    ok = vkEndCommandBuffer(cmd) == VK_SUCCESS;
  }
  if (ok) {
    VkSubmitInfo si {};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
    if (isSignal) {
      si.signalSemaphoreCount = 1;
      si.pSignalSemaphores = &semaphore;
    }
    else {
      si.waitSemaphoreCount = 1;
      si.pWaitSemaphores = &semaphore;
      si.pWaitDstStageMask = &waitStage;
    }
    ok = vkQueueSubmit(queue, 1, &si, VK_NULL_HANDLE) == VK_SUCCESS &&
         vkQueueWaitIdle(queue) == VK_SUCCESS;
  }
  vkFreeCommandBuffers(device, pool, 1, &cmd);
  return ok;
}

bool
SoRTXRenderBackend::signalRtxVkToCudaSemaphore()
{
  if (this->rtxVkToCudaSignalPending) {
    return true;
  }
  if (!this->rtxInteropSemaphoresReady ||
      this->rtxVkToCudaSem == VK_NULL_HANDLE) {
    return false;
  }
  if (!submitRtxSemaphoreBarrier(this->device, this->transientPool,
                                 this->queue, this->allocator,
                                 this->rtxVkToCudaSem, true)) {
    return false;
  }
  this->rtxVkToCudaSignalPending = true;
  return true;
}

bool
SoRTXRenderBackend::consumeVulkanSemaphore(VkSemaphore semaphore)
{
  return submitRtxSemaphoreBarrier(this->device, this->transientPool,
                                   this->queue, this->allocator, semaphore,
                                   false);
}

bool
SoRTXRenderBackend::updateRtxDenoise(uint32_t w, uint32_t h,
                                     bool signalCudaToVulkan)
{
  if (!this->rtxDenoiser || !this->rtxCudaCtx) return false;
  if (!this->rtxInteropReady) return false;
  this->rtxCudaSignalPending = false;

  // The color image holds the accumulated sum (rgb) with the sample count in
  // w; normalize to the average color in place before OptiX runs.
  if (cuCtxSetCurrent(this->rtxCudaCtx) != CUDA_SUCCESS) return false;

  if (this->rtxInteropSemaphoresReady) {
    if (this->signalRtxVkToCudaSemaphore()) {
      CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS waitParams {};
      waitParams.flags = 0;
      if (cuWaitExternalSemaphoresAsync(&this->rtxVkToCudaCudaSem,
                                        &waitParams, 1,
                                        this->rtxStream) == CUDA_SUCCESS) {
        this->rtxVkToCudaSignalPending = false;
      }
      else {
        const CUresult syncRes = cuStreamSynchronize(this->rtxStream);
        if (syncRes != CUDA_SUCCESS) {
          char msg[176];
          std::snprintf(msg, sizeof(msg),
                        "signalRtxVkToCudaSemaphore: cuStreamSynchronize "
                        "failed (CUDA result %d)", static_cast<int>(syncRes));
          this->emitError(msg);
        }
        if (this->rtxVkToCudaSignalPending) {
          this->consumeVulkanSemaphore(this->rtxVkToCudaSem);
          this->rtxVkToCudaSignalPending = false;
        }
        if (this->queue != VK_NULL_HANDLE) {
          this->drainQueue("RTX denoiser (CUDA semaphore-wait fallback)");
        }
      }
    }
    else if (this->queue != VK_NULL_HANDLE) {
      this->drainQueue("RTX denoiser (CUDA semaphore-signal fallback)");
    }
  }
  else if (this->queue != VK_NULL_HANDLE) {
    this->drainQueue("RTX denoiser (no interop semaphore)");
  }

  {
    unsigned int n = w * h;
    const unsigned int blocks = (n + 255u) / 256u;
    void * argn[] = {&this->rtxColorImage, &n};
    if (cuLaunchKernel(this->rtxNormKernel, blocks, 1, 1, 256, 1, 1, 0,
                       this->rtxStream, argn, nullptr) != CUDA_SUCCESS) {
      return false;
    }
  }

  // Configure the input/output layers.
  OptixImage2D colorImage {};
  colorImage.data = this->rtxColorImage;
  colorImage.width = w;
  colorImage.height = h;
  colorImage.rowStrideInBytes = static_cast<unsigned int>(this->rtxImagePitch);
  colorImage.pixelStrideInBytes = 4 * sizeof(float);
  colorImage.format = OPTIX_PIXEL_FORMAT_FLOAT4;

  OptixImage2D albedoImage = colorImage;
  albedoImage.data = this->rtxAlbedoImage;
  OptixImage2D normalImage = colorImage;
  normalImage.data = this->rtxNormalImage;
  // Motion flow guide.  The flow field is a per-pixel FLOAT2 screen-space
  // NDC vector; our motion buffer is FLOAT4 (x,y = NDC delta, z = validity),
  // so a 16-byte pixel stride reads the leading two components.  This guide
  // is only consumed by the TEMPORAL model kinds; the AOV model ignores it,
  // so leaving it zero-validated against a real image is harmless.
  OptixImage2D motionImage = colorImage;
  motionImage.data = this->rtxMotionImage;
  motionImage.pixelStrideInBytes = 4 * sizeof(float);
  motionImage.format = OPTIX_PIXEL_FORMAT_FLOAT2;
  OptixImage2D outputImage = colorImage;
  outputImage.data = this->rtxOutputImage;

  OptixDenoiserGuideLayer guide {};
  guide.albedo = albedoImage;
  guide.normal = normalImage;
  guide.flow = motionImage;

  OptixDenoiserLayer layer {};
  layer.input = colorImage;
  layer.output = outputImage;
  layer.type = OPTIX_DENOISER_AOV_TYPE_BEAUTY;

  // Compute the scene exposure from the average color (auto-exposure), then
  // set up the denoiser state and invoke.  All three must run on the SAME
  // stream: optixDenoiserComputeIntensity writes hdrIntensity
  // (this->rtxIntensity) and optixDenoiserInvoke reads it via params, and a
  // cross-stream split with no ordering leaves the invoke racing the
  // intensity write (the nvpro vk_optix_denoise example uses one stream).
  OptixDenoiserParams params {};
  params.hdrIntensity = this->rtxIntensity;
  params.blendFactor = 0.0f;

  if (optixDenoiserComputeIntensity(this->rtxDenoiser, this->rtxStream,
                                    &colorImage, this->rtxIntensity,
                                    this->rtxScratch,
                                    this->rtxScratchBytes) != OPTIX_SUCCESS) {
    return false;
  }
  if (optixDenoiserSetup(this->rtxDenoiser, this->rtxStream, w, h,
                         this->rtxState, this->rtxStateBytes,
                         this->rtxScratch, this->rtxScratchBytes) !=
      OPTIX_SUCCESS) {
    return false;
  }
  if (optixDenoiserInvoke(this->rtxDenoiser, this->rtxStream, &params,
                          this->rtxState, this->rtxStateBytes, &guide, &layer,
                          1, 0, 0, this->rtxScratch,
                          this->rtxScratchBytes) != OPTIX_SUCCESS) {
    return false;
  }

  bool signalQueued = false;
  if (this->rtxInteropSemaphoresReady && signalCudaToVulkan &&
      this->rtxCudaToVkSem != VK_NULL_HANDLE) {
    CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS sig {};
    sig.flags = 0;
    signalQueued =
      cuSignalExternalSemaphoresAsync(&this->rtxCudaToVkCudaSem, &sig, 1,
                                      this->rtxStream) == CUDA_SUCCESS;
  }

  if (cuStreamSynchronize(this->rtxStream) != CUDA_SUCCESS) {
    if (signalQueued) {
      this->consumeVulkanSemaphore(this->rtxCudaToVkSem);
    }
    this->rtxCudaSignalPending = false;
    if (this->queue != VK_NULL_HANDLE) {
      this->drainQueue("RTX denoiser (CUDA stream error)");
    }
    return false;
  }

  this->rtxCudaSignalPending = signalQueued;
  if (this->queue != VK_NULL_HANDLE) {
    this->drainQueue("RTX denoiser (post-signal)");
  }
  return true;
}
#endif // COIN_BUILD_RTX_DENOISER
