// src/rendering/SoRTXRenderBackend/SoRTXRenderBackendDenoise.cpp

// Split from the original monolithic SoRTXRenderBackend.cpp.  Contains the
// "Denoise" concern of the Vulkan RTX backend: the table of contents selects
// one of the external denoiser backends (Intel OIDN on the CPU/GPU, NVIDIA
// RTX via OptiX + CUDA, or AMD FSR) that the path tracer feeds its first-
// bounce G-buffers into, and publishes the denoised rgba into the present
// descriptor set's DenoisedBuffer (binding 5).
//
// The G-buffers written by the raygen are device-local storage buffers:
//   - accumBuffer   (binding 4)  rgba: rgb = radiance sum, a = sample count
//   - albedoBuffer  (binding 14) rgba: rgb = first-hit albedo, a = validity
//   - normalBuffer  (binding 5)  rgba: rgb = world normal, a = valid
//   - positionBuffer(binding 6)  rgba: rgb = world position, a = hit distance
// The denoiser wants a per-pixel color/average plus albedo and normal guides.
// To move them between Vulkan and the denoiser, the hub device-local buffers
// are copied into host-visible staging (recordDenoiseReadback, on the one-shot
// command buffer), the denoiser runs after the submission's queue wait
// (updateDenoise), and the result is copied back into the device-local
// denoisedBuffer bound at present binding 5.

#include "rendering/SoRTXRenderBackend.h"
#include <Inventor/errors/SoDebugError.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstring>
#include <string>
#include <rendering/SoRTXRenderBackend/SoRTXRenderBackendP.h>

#if COIN_BUILD_RTX_DENOISER
// The OptiX function table lives in exactly this TU.
#include <optix_function_table_definition.h>
#include <thread>
#include <vector>
#include <cstdio>
#include <cerrno>
#include <fcntl.h>
#include <unistd.h>
#endif

using namespace SoRTXBackend;

#if COIN_BUILD_RTX_DENOISER
// PTX for the sum->average normalizer (compiled with nvcc -ptx -arch=sm_75).
// Converts an accumulated radiance sum (rgb) / sample-count (w) buffer into
// the average color (and sets w = 1 for valid pixels, 0 for empty ones) that
// the OptiX AOV denoiser expects as its AOV beauty input.
namespace fca_rtx {
const char * kCointerpNormalizePtx =
"//\n"
"// Generated by NVIDIA NVVM Compiler\n"
"//\n"
"// Compiler Build ID: CL-38244171\n"
"// Cuda compilation tools, release 13.3, V13.3.73\n"
"// Based on NVVM 23.0.0\n"
"//\n"
"\n"
".version 9.3\n"
".target sm_75\n"
".address_size 64\n"
"\n"
"	// .globl	cointerp_normalize\n"
"\n"
".visible .entry cointerp_normalize(\n"
"	.param .u64 .ptr .align 1 cointerp_normalize_param_0,\n"
"	.param .u32 cointerp_normalize_param_1\n"
")\n"
"{\n"
"	.reg .pred 	%p<4>;\n"
"	.reg .b32 	%r<16>;\n"
"	.reg .b64 	%rd<5>;\n"
"\n"
"	ld.param.b64 	%rd2, [cointerp_normalize_param_0];\n"
"	ld.param.b32 	%r3, [cointerp_normalize_param_1];\n"
"	mov.u32 	%r4, %ctaid.x;\n"
"	mov.u32 	%r5, %ntid.x;\n"
"	mov.u32 	%r6, %tid.x;\n"
"	mad.lo.s32 	%r1, %r4, %r5, %r6;\n"
"	setp.ge.s32 	%p1, %r1, %r3;\n"
"	@%p1 bra 	$L__BB0_4;\n"
"	cvta.to.global.u64 	%rd3, %rd2;\n"
"	mul.wide.s32 	%rd4, %r1, 16;\n"
"	add.s64 	%rd1, %rd3, %rd4;\n"
"	ld.global.b32 	%r7, [%rd1+12];\n"
"	abs.f32 	%r8, %r7;\n"
"	setp.gt.f32 	%p2, %r8, 0f3727C5AC;\n"
"	selp.f32 	%r2, %r7, 0f00000000, %p2;\n"
"	setp.leu.f32 	%p3, %r2, 0f00000000;\n"
"	@%p3 bra 	$L__BB0_3;\n"
"	.pragma \"used_bytes_mask 0xfff\";\n"
"	ld.global.v4.b32 	{%r9, %r10, %r11, %r12}, [%rd1];\n"
"	div.rn.f32 	%r13, %r9, %r2;\n"
"	div.rn.f32 	%r14, %r10, %r2;\n"
"	div.rn.f32 	%r15, %r11, %r2;\n"
"	st.global.v4.b32 	[%rd1], {%r13, %r14, %r15, 0f3F800000};\n"
"	bra.uni 	$L__BB0_4;\n"
"$L__BB0_3:\n"
"	st.global.b32 	[%rd1+12], 0;\n"
"$L__BB0_4:\n"
"	ret;\n"
"\n"
"}\n";
} // namespace fca_rtx
using fca_rtx::kCointerpNormalizePtx;
#endif // COIN_BUILD_RTX_DENOISER

void
SoRTXRenderBackend::setupOidnDevice()
{
#if COIN_BUILD_OIDN
  if (this->oidnDevice) return;
  // We feed the denoiser from host-visible staging (oidnSetSharedFilterImage
  // with CPU pointers), so a CPU device is the correct target.  If the user
  // explicitly selects a CUDA device the staging would need to be device
  // memory; keep it simple and robust with the CPU device.
  this->oidnDevice = oidnNewDevice(OIDN_DEVICE_TYPE_CPU);
  if (!this->oidnDevice) {
    this->emitError("OIDN denoiser: failed to create a CPU device");
    return;
  }
  oidnCommitDevice(this->oidnDevice);
#endif
}

bool
SoRTXRenderBackend::configureOidnFilter()
{
#if COIN_BUILD_OIDN
  this->setupOidnDevice();
  if (!this->oidnDevice) {
    if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
      fprintf(stderr, "[DENOISE] OIDN device null\n");
    }
    return false;
  }
  if (this->oidnFilter) return true;
  this->oidnFilter = oidnNewFilter(this->oidnDevice, "RT");
  if (!this->oidnFilter) {
    this->emitError("OIDN denoiser: failed to create RT filter");
    return false;
  }
  // RT filter: HDR path-tracer radiance, use the albedo + normal guides, at
  // interactive quality (the denoiser runs each accumulated frame).
  oidnSetFilterBool(this->oidnFilter, "hdr", true);
  oidnSetFilterInt(this->oidnFilter, "quality", OIDN_QUALITY_BALANCED);
  return true;
#else
  return false;
#endif
}

bool
SoRTXRenderBackend::createDenoiseBackend()
{
  if (this->denoiseWidth == 0 || this->denoiseHeight == 0) return false;
  // Resize: if the staging/output already exist but the resolution changed,
  // tear them down first so they are recreated at the new dimensions.  A
  // runtime denoiser change (denoiseKindDirty, set by setDenoiserFilter)
  // forces the same teardown so the new backend is configured on the next
  // frame even without a resize.
  if (this->denoisedBuffer != VK_NULL_HANDLE &&
      (this->denoiseStagedWidth != this->denoiseWidth ||
       this->denoiseStagedHeight != this->denoiseHeight ||
       this->denoiseKindDirty)) {
    // destroyDenoiser() is a full teardown that zeroes denoiseWidth/Height,
    // but here we are mid-recreation at the same working resolution; snapshot
    // the dimensions (and re-set them) so the rest of createDenoiseBackend()
    // still allocates the buffers at the current extent instead of falling
    // through to a zero-size allocation (an nvidia zero-size device object
    // returns VK_ERROR_DEVICE_LOST and poisons the frame).
    const uint32_t width = this->denoiseWidth;
    const uint32_t height = this->denoiseHeight;
    this->destroyDenoiser();
    this->denoiseWidth = width;
    this->denoiseHeight = height;
  }
  if (this->denoisedBuffer != VK_NULL_HANDLE) return true;

  // Resolve the backend from the user's stored choice.  The preference set by
  // setDenoiserFilter() (denoiseKindPref) survives the teardown above, so a
  // viewport resize or runtime denoiser change re-creates the SAME backend
  // instead of silently falling back to the OIDN CPU device.  The
  // FC_VULKAN_PT_DENOISER env var seeds denoiseKindPref on the first
  // resolution.  Only when nothing was specified do we default to OIDN.
  // FSR degrades to OIDN when the FFX SDK is not built in.
  // Always re-resolve from denoiseKindPref: destroyDenoiser() (called above on
  // a resize or a runtime denoiser switch) zeroes denoiseKind, so restoring it
  // from the preference unconditionally is what makes a runtime
  // setDenoiserFilter() -> createDenoiseBackend() transition actually take
  // effect instead of leaving the denoiser inactive (denoiseKind == None).
  this->denoiseKind = this->denoiseKindPref;
  if (this->denoiseKind != DenoiseRtx && this->denoiseKind != DenoiseOidn &&
      this->denoiseKind != DenoiseFsr && this->denoiseKind != DenoiseNone) {
    this->denoiseKind = DenoiseOidn;
  }
  if (!this->denoiseKindExplicit && this->denoiseKindPref == DenoiseNone) {
    // First resolution, no explicit preference: honour the env var, then fall
    // back to the default (OIDN).  An explicit "none" selection is a real
    // user choice and must not be overwritten by the env/default fallback.
    if (const char * sel = getenv("FC_VULKAN_PT_DENOISER")) {
      if (std::strcmp(sel, "rtx") == 0) {
        this->denoiseKind = DenoiseRtx;
        this->denoiseKindPref = DenoiseRtx;
      }
      else if (std::strcmp(sel, "fsr") == 0) {
        this->denoiseKind = DenoiseFsr;
        this->denoiseKindPref = DenoiseFsr;
      }
      else if (std::strcmp(sel, "none") == 0) {
        this->denoiseKind = DenoiseNone;
        this->denoiseKindPref = DenoiseNone;
      }
      else {
        this->denoiseKind = DenoiseOidn;
        this->denoiseKindPref = DenoiseOidn;
      }
    }
    else {
      this->denoiseKind = DenoiseOidn;
      this->denoiseKindPref = DenoiseOidn;
    }
    this->denoiseKindExplicit = true;
  }
  this->denoiseKindDirty = false;

  if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
    fprintf(stderr,
            "[DENOISE] resolved kind=%d explicit=%d pref=%d ptEnabled=%d\n",
            static_cast<int>(this->denoiseKind),
            this->denoiseKindExplicit ? 1 : 0,
            static_cast<int>(this->denoiseKindPref),
            this->ptEnabled ? 1 : 0);
  }

  // Compute the denoiser working resolution.  A scale factor >1 lets the
  // denoiser run at reduced resolution (cheaper) and the raster present pass
  // upscales; the present push constant carries denoiseScale.  For now we
  // denoise at native resolution (scale 1) so guides align 1:1 with the
  // present shader's pixel grid.
  this->denoiseScale = 1.0f;

  if (this->denoiseKind == DenoiseNone || !this->ptEnabled) {
    return true;
  }

  // Set when the host-visible staging block (OIDN/FSR) cannot be allocated;
  // the device-local denoised/albedo buffers still get created so descriptor
  // bindings stay valid, but the host-side denoiser backends are skipped.
  bool stagingFailed = false;

  // Host-visible staging buffers: one mapped block covering color, albedo,
  // normal, motion and output for the current resolution.  Allocates a single
  // host-visible buffer so the maps stay valid for the life of the backend
  // and the denoiser can read the G-buffer rows directly.  Regions are laid
  // out as [0]=color, [1]=albedo, [2]=normal, [3]=motion, [4]=output (the
  // readback copies the four inputs and the denoiser writes one output).
  // The real per-pixel validity comes from the sample count in color[3], so
  // the position buffer is never staged.  The block is 5x imageBytes -- the
  // four inputs plus the output -- which is the working set a host-side
  // denoiser needs; anything larger just wastes host-visible memory, the
  // constrained resource that fails the allocation.
  //
  // The RTX path needs no host staging: it copies the G-buffers device-to-
  // device into CUDA-Vulkan interop images and runs OptiX entirely on the
  // GPU, so skip the host-coherent block (several image-sized regions is the
  // exact allocation that can run the driver out of host-visible memory) and
  // only allocate it for the host-side OIDN/FSR backends.
  const VkDeviceSize pixelBytes = 4 * sizeof(float);
  const VkDeviceSize imageBytes =
    static_cast<VkDeviceSize>(this->denoiseWidth) * this->denoiseHeight *
    pixelBytes;
  if (this->denoiseKind != DenoiseRtx) {
    const VkDeviceSize totalBytes = imageBytes * 5; // color+albedo+normal+motion+out
    if (!this->createHostVisibleBuffer(
          totalBytes, VK_BUFFER_USAGE_TRANSFER_DST_BIT |
            VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
            VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
          this->denoiseColorBuf, this->denoiseColorMem)) {
      // The host-visible staging block is the constrained allocation (several
      // image-sized regions at viewport resolution); if the driver cannot back
      // it, degrade gracefully rather than failing the whole path-tracing
      // buffer setup (which previously cascaded through createPathTracingBuffers
      // into renderExternal and VK_ERROR_DEVICE_LOST).  Mark the staging as
      // unavailable so the OIDN/FSR backends are skipped, but keep going so
      // the device-local denoised/albedo buffers (which the present shader
      // bindings depend on) are still created and the descriptors stay valid.
      this->emitError("failed to create denoiser staging buffer; disabling denoiser");
      stagingFailed = true;
    }
    else {
      // The four logical regions share one backing allocation; derive the
      // handles by offset.  We keep VkBuffer handles identical (the staging
      // buffer) and only the mapped pointers differ, which is fine for the
      // host-side denoisers.
      this->denoiseAlbedoBuf = this->denoiseColorBuf;
      this->denoiseNormalBuf = this->denoiseColorBuf;
      this->denoiseGuideBuf = this->denoiseColorBuf;
      this->denoiseMotionBuf = this->denoiseColorBuf;
      this->denoiseOutBuf = this->denoiseColorBuf;
      this->denoiseAlbedoMem = this->denoiseColorMem;
      this->denoiseNormalMem = this->denoiseColorMem;
      this->denoiseGuideMem = this->denoiseColorMem;
      this->denoiseMotionMem = this->denoiseColorMem;
      this->denoiseOutMem = this->denoiseColorMem;
      if (vkMapMemory(this->device, this->denoiseColorMem, 0, totalBytes, 0,
                      &this->denoiseStagingPtr) != VK_SUCCESS) {
        this->denoiseStagingPtr = nullptr;
        this->emitError("failed to map denoiser staging buffer; disabling denoiser");
        stagingFailed = true;
      }
    }
  }

  // Device-local output image bound at present binding 5.  The present
  // shader reads it as a StorageBuffer of vec4.
  if (!this->createDeviceLocalBuffer(
        imageBytes, VK_BUFFER_USAGE_TRANSFER_DST_BIT |
          VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
        this->denoisedBuffer, this->denoisedMemory)) {
    this->emitError("failed to create denoised output buffer");
    return false;
  }

  // Albedo G-buffer (binding 14): written by the raygen and read back as the
  // albedo guide.  Device-local STORAGE + TRANSFER_SRC so the readback can
  // copy it to host staging.  Refresh descriptors once after both it and the
  // denoised output exist so no descriptor is left unwritten/undefined.
  if (this->albedoBuffer == VK_NULL_HANDLE) {
    if (!this->createDeviceLocalBuffer(
          imageBytes, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
            VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
          this->albedoBuffer, this->albedoMemory)) {
      this->emitError("failed to create albedo G-buffer");
      return false;
    }
    if (!this->updateDescriptors()) {
      this->emitError("failed to refresh descriptors for albedo buffer");
      return false;
    }
  }

  // Backend-specific setup.
#if COIN_BUILD_OIDN
  if (this->denoiseKind == DenoiseOidn) {
    if (stagingFailed || !this->configureOidnFilter()) {
      this->emitError("OIDN denoiser unavailable; disabling denoise");
      this->denoiseKind = DenoiseNone;
    }
  }
#endif

#if COIN_BUILD_RTX_DENOISER
  if (this->denoiseKind == DenoiseRtx) {
    this->rtxModelKind = [this]() {
      const char * m = getenv("FC_VULKAN_PT_RTX_MODEL");
      if (m && std::strcmp(m, "TEMPORAL") == 0)
        return OPTIX_DENOISER_MODEL_KIND_TEMPORAL_AOV;
      if (m && std::strcmp(m, "ALBEDO") == 0) return OPTIX_DENOISER_MODEL_KIND_AOV;
      return OPTIX_DENOISER_MODEL_KIND_AOV;
    }();

    // The CUDA/OptiX denoiser runs by importing Vulkan device memory into
    // CUDA (VK_KHR_external_memory_fd) and is therefore only valid when the
    // Vulkan device is an NVIDIA GPU.  The ray-query path tracer itself is
    // vendor-neutral: on an AMD/Intel RT-capable device it renders fine, so
    // only the denoiser must be gated here and degraded to OIDN.
    if (!this->deviceIsNvidia) {
      if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
        fprintf(stderr,
                "[DENOISE] RTX denoiser unavailable: Vulkan device vendor "
                "0x%04x is not NVIDIA; using OIDN\n",
                this->deviceVendorID);
      }
      this->denoiseKind = DenoiseOidn;
#if COIN_BUILD_OIDN
      if (!this->configureOidnFilter()) {
        this->emitError("OIDN fallback unavailable; disabling denoise");
        this->denoiseKind = DenoiseNone;
      }
#endif
    }
    else if (this->initRtxCuda() && this->initRtxDenoiser()) {
      this->denoiserActive = true;
    }
    else {
      this->emitError("RTX denoiser unavailable; degrading to OIDN");
      // Free only the CUDA/OptiX state; the staging buffers (Vulkan) are
      // still valid and the OIDN filter below reuses them.
      this->teardownRtxDenoiser();
      this->denoiseKind = DenoiseOidn;
#if COIN_BUILD_OIDN
      if (!this->configureOidnFilter()) {
        this->emitError("OIDN fallback unavailable; disabling denoise");
        this->denoiseKind = DenoiseNone;
      }
#endif
    }
  }
#endif

  if (this->denoiseKind == DenoiseFsr) {
#if COIN_BUILD_FSR_DENOISER
    // FSR setup would go here once the AMD FFX SDK is wired into the build.
#endif
    // FSR is not implemented (the SDK is an optional drop-in; see CMakeLists).
    // Keep the degradation OUTSIDE the build guard so selecting "fsr" always
    // falls back to OIDN with a message instead of leaving the denoiser
    // inactive: with denoiseKind still FSR the configured check below matches
    // neither OIDN nor RTX and the denoiser turns off (raw grainy output).
    this->emitError("AMD FSR denoiser is not built in; falling back to OIDN");
    this->denoiseKind = DenoiseOidn;
#if COIN_BUILD_OIDN
    if (!this->configureOidnFilter()) {
      this->emitError("OIDN fallback unavailable; disabling denoise");
      this->denoiseKind = DenoiseNone;
    }
#endif
  }

  // Confirm a backend was actually configured for the resolved kind.  The
  // degraded paths above reset denoiseKind to Oidn and reconfigure the OIDN
  // filter; if none of the built backends could configure (e.g. OIDN not
  // linked and RTX unavailable) the denoiser stays inactive so the frame
  // loop does not bother recording readbacks it can never service.
  bool configured = false;
#if COIN_BUILD_OIDN
  if (this->denoiseKind == DenoiseOidn && this->oidnFilter) configured = true;
#endif
#if COIN_BUILD_RTX_DENOISER
  if (this->denoiseKind == DenoiseRtx && this->rtxDenoiser) configured = true;
#endif
  if (!configured) {
    if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
      fprintf(stderr, "[DENOISE] no backend configured for kind=%d\n",
              static_cast<int>(this->denoiseKind));
    }
    this->denoiserActive = false;
    this->releaseDenoiseStaging();
    return true;
  }
  this->denoiserActive = true;
  this->denoiseStagedWidth = this->denoiseWidth;
  this->denoiseStagedHeight = this->denoiseHeight;
  if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
    fprintf(stderr, "[DENOISE] backend configured kind=%d active=%s\n",
            static_cast<int>(this->denoiseKind),
            this->denoiserActive ? "yes" : "no");
  }
  return true;
}

void
SoRTXRenderBackend::submitDenoiseCopy(VkCommandBuffer cmd)
{
  const bool async = getenv("FC_VULKAN_ASYNC_COMPUTE") != nullptr &&
    this->hasComputeQueue && this->computeQueue != VK_NULL_HANDLE;
  VkQueue q = async ? this->computeQueue : this->queue;
  VkSubmitInfo si {};
  si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
  si.commandBufferCount = 1;
  si.pCommandBuffers = &cmd;
  if (async) {
    // Submit on the compute queue so the graphics queue stays free to process
    // other submits while the denoiser output copy runs.  When the timeline
    // semaphore is available the completion is signalled as a timeline value
    // and the host waits on that exact value with vkWaitSemaphores; otherwise
    // fall back to a binary fence wait.
    if (this->ensureAsyncComputeTimeline() && this->vkWaitSemaphores) {
      const uint64_t value = ++this->asyncComputeTimelineValue;
      VkSemaphoreSubmitInfo signal {};
      signal.sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO;
      signal.semaphore = this->asyncComputeTimeline;
      signal.stageMask = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
      signal.value = value;
      VkTimelineSemaphoreSubmitInfo tls {};
      tls.sType = VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO;
      tls.signalSemaphoreValueCount = 1;
      tls.pSignalSemaphoreValues = &value;
      VkSemaphore sem = this->asyncComputeTimeline;
      si.signalSemaphoreCount = 1;
      si.pSignalSemaphores = &sem;
      si.pNext = &tls;
      vkQueueSubmit(q, 1, &si, VK_NULL_HANDLE);
      VkSemaphoreWaitInfo wi {};
      wi.sType = VK_STRUCTURE_TYPE_SEMAPHORE_WAIT_INFO;
      wi.semaphoreCount = 1;
      wi.pSemaphores = &this->asyncComputeTimeline;
      wi.pValues = &value;
      vkWaitSemaphores(this->device, &wi, UINT64_MAX);
      if (getenv("FC_VULKAN_ASYNC_COMPUTE_TIMING")) {
        fprintf(stderr, "[ASYNC] compute copy signalled timeline value=%llu\n",
                static_cast<unsigned long long>(value));
      }
      return;
    }
    // Timeline semaphore unavailable: block on a fence (the graphics queue is
    // still left free); a missing fence falls back to a blocking submit.
    VkFence fence = VK_NULL_HANDLE;
    VkFenceCreateInfo fci {};
    fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    if (vkCreateFence(this->device, &fci, this->allocator, &fence) !=
          VK_SUCCESS ||
        fence == VK_NULL_HANDLE) {
      vkQueueSubmit(q, 1, &si, VK_NULL_HANDLE);
      vkQueueWaitIdle(q);
      return;
    }
    vkQueueSubmit(q, 1, &si, fence);
    vkWaitForFences(this->device, 1, &fence, VK_TRUE, UINT64_MAX);
    vkDestroyFence(this->device, fence, this->allocator);
  }
  else {
    vkQueueSubmit(q, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(q);
  }
}

bool
SoRTXRenderBackend::ensureAsyncComputeTimeline()
{
  if (this->asyncComputeTimeline != VK_NULL_HANDLE) {
    return this->vkWaitSemaphores != nullptr;
  }
  if (this->device == VK_NULL_HANDLE) return false;
  // vkWaitSemaphores is a Vulkan 1.2 core device function; resolve it the
  // same way the KHR entry points are (the loader only exports core 1.0).
  PFN_vkVoidFunction fn = vkGetDeviceProcAddr(this->device, "vkWaitSemaphores");
  if (fn == nullptr) return false;
  this->vkWaitSemaphores = loadDispatch<PFN_vkWaitSemaphores>(fn);
  VkSemaphoreTypeCreateInfo typeInfo {};
  typeInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO;
  typeInfo.semaphoreType = VK_SEMAPHORE_TYPE_TIMELINE;
  typeInfo.initialValue = 0;
  VkSemaphoreCreateInfo sci {};
  sci.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
  sci.pNext = &typeInfo;
  if (vkCreateSemaphore(this->device, &sci, this->allocator,
                        &this->asyncComputeTimeline) != VK_SUCCESS) {
    this->asyncComputeTimeline = VK_NULL_HANDLE;
    this->vkWaitSemaphores = nullptr;
    return false;
  }
  this->asyncComputeTimelineValue = 0;
  if (getenv("FC_VULKAN_ASYNC_COMPUTE_TIMING")) {
    fprintf(stderr, "[ASYNC] created compute timeline semaphore\n");
  }
  return true;
}

void
SoRTXRenderBackend::destroyAsyncComputeTimeline()
{
  if (this->asyncComputeTimeline != VK_NULL_HANDLE) {
    vkDestroySemaphore(this->device, this->asyncComputeTimeline,
                       this->allocator);
    this->asyncComputeTimeline = VK_NULL_HANDLE;
  }
  this->vkWaitSemaphores = nullptr;
  this->asyncComputeTimelineValue = 0;
}

void
SoRTXRenderBackend::recordDenoiseReadback(VkCommandBuffer cmd)
{
  if (!this->denoiserActive) return;
  const VkDeviceSize stride =
    static_cast<VkDeviceSize>(this->denoiseWidth) * this->denoiseHeight * 16;

#if COIN_BUILD_RTX_DENOISER
  // RTX reads the G-buffers through the CUDA-Vulkan interop images: the
  // denoiser kernel (OptiX) is imported over the same device memory, so the
  // G-buffers are copied device-to-device and no host staging is involved.
  if (this->denoiseKind == DenoiseRtx && this->rtxInteropReady) {
    VkMemoryBarrier before {};
    before.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    before.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    before.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR |
                              VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                         VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 1, &before, 0,
                         nullptr, 0, nullptr);

    if (this->accumBuffer != VK_NULL_HANDLE && this->rtxColorVk != VK_NULL_HANDLE) {
      VkBufferCopy c0 {0, 0, stride};
      vkCmdCopyBuffer(cmd, this->accumBuffer, this->rtxColorVk, 1, &c0);
    }
    if (this->albedoBuffer != VK_NULL_HANDLE && this->rtxAlbedoVk != VK_NULL_HANDLE) {
      VkBufferCopy c1 {0, 0, stride};
      vkCmdCopyBuffer(cmd, this->albedoBuffer, this->rtxAlbedoVk, 1, &c1);
    }
    if (this->normalBuffer != VK_NULL_HANDLE && this->rtxNormalVk != VK_NULL_HANDLE) {
      VkBufferCopy c2 {0, 0, stride};
      vkCmdCopyBuffer(cmd, this->normalBuffer, this->rtxNormalVk, 1, &c2);
    }
    if (this->motionBuffer != VK_NULL_HANDLE && this->rtxMotionVk != VK_NULL_HANDLE) {
      VkBufferCopy cM {0, 0, stride};
      vkCmdCopyBuffer(cmd, this->motionBuffer, this->rtxMotionVk, 1, &cM);
    }

    // Make the copies visible to the CUDA driver (COMPUTE stage) after the
    // Vulkan queue waits idle.
    VkMemoryBarrier afterStaging {};
    afterStaging.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    afterStaging.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    afterStaging.dstAccessMask = VK_ACCESS_SHADER_READ_BIT |
                                 VK_ACCESS_SHADER_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1,
                         &afterStaging, 0, nullptr, 0, nullptr);
    this->oidnReadbackPending = TRUE;
    return;
  }
#endif

  // Host-side denoisers (OIDN/FSR): copy into the mapped staging allocation.
  // The host-visible staging buffer is one allocation with five sequential
  // image-sized regions; the denoiser indexes them via denoiseStagingPtr +
  // region offset.
  if (this->denoiseColorBuf == VK_NULL_HANDLE) return;
  if (this->accumBuffer == VK_NULL_HANDLE) return;

  VkMemoryBarrier before {};
  before.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
  before.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
  before.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
  vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR |
                            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                       VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 1, &before, 0,
                       nullptr, 0, nullptr);

  // color (accum average), albedo, normal, motion.  The position buffer is not
  // needed: the present shader's denoised-alpha test uses the averaged color's
  // w (set from the sample count in updateDenoise), which distinguishes empty
  // pixels from ones with a primary hit.
  VkBufferCopy c0 {0, 0, stride};
  vkCmdCopyBuffer(cmd, this->accumBuffer, this->denoiseColorBuf, 1, &c0);
  if (this->albedoBuffer != VK_NULL_HANDLE) {
    VkBufferCopy c1 {0, stride, stride};
    vkCmdCopyBuffer(cmd, this->albedoBuffer, this->denoiseColorBuf, 1, &c1);
  }
  if (this->normalBuffer != VK_NULL_HANDLE) {
    VkBufferCopy c2 {0, 2 * stride, stride};
    vkCmdCopyBuffer(cmd, this->normalBuffer, this->denoiseColorBuf, 1, &c2);
  }
  if (this->motionBuffer != VK_NULL_HANDLE) {
    VkBufferCopy cM {0, 3 * stride, stride};
    vkCmdCopyBuffer(cmd, this->motionBuffer, this->denoiseColorBuf, 1, &cM);
  }

  VkMemoryBarrier afterStaging {};
  afterStaging.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
  afterStaging.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
  afterStaging.dstAccessMask = VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT;
  vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                       VK_PIPELINE_STAGE_HOST_BIT, 0, 1, &afterStaging, 0,
                       nullptr, 0, nullptr);
  this->oidnReadbackPending = TRUE;
}

void
SoRTXRenderBackend::updateDenoise()
{
  if (!this->denoiserActive || this->denoisedBuffer == VK_NULL_HANDLE) return;

#if COIN_BUILD_OIDN
  // Async OIDN completion handoff.  The worker owns the staging block and the
  // OIDN filter from the moment the denoise-at-target launched until it sets
  // oidnWorkerDone.  These two states are handled here, before the
  // ptDenoisePending gating below, so the copy-back and converge run exactly
  // once the worker publishes, independent of whether the target latch is
  // still set, and the in-flight case does not fall through to the "no
  // denoiser ran" convergence below.
  if (this->oidnWorkerDone) {
    // Worker published the denoised result in the staging output region.
    // Snap the resolved dimensions (stored at backend creation; the staging
    // well is stable for the life of the backend).
    const uint32_t w = this->denoiseWidth;
    const uint32_t h = this->denoiseHeight;
    const VkDeviceSize stride = static_cast<VkDeviceSize>(w) * h * 16;
    if (this->oidnWorker.joinable()) {
      this->oidnWorker.join();
    }
    this->oidnWorkerDone = FALSE;
    this->oidnWorkerRunning = FALSE;
    if (w > 0 && h > 0 && this->denoiseOutBuf != VK_NULL_HANDLE) {
      // Copy the denoiser output back to the device-local denoisedBuffer
      // (present binding 5) on a one-shot command buffer, then publish the
      // result.  The frame's own submission has already been waited on, and
      // the staging is HOST_COHERENT so the worker's writes are visible here.
      VkCommandBuffer cmd = this->beginTransientCommandBuffer();
      if (cmd != VK_NULL_HANDLE) {
        VkMemoryBarrier hostBar {};
        hostBar.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
        hostBar.srcAccessMask = VK_ACCESS_HOST_WRITE_BIT;
        hostBar.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_HOST_BIT,
                             VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 1, &hostBar, 0,
                             nullptr, 0, nullptr);
        VkBufferCopy cOut {4 * stride, 0, stride};
        vkCmdCopyBuffer(cmd, this->denoiseOutBuf, this->denoisedBuffer, 1,
                        &cOut);
        VkMemoryBarrier outBar {};
        outBar.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
        outBar.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        outBar.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                             VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 1,
                             &outBar, 0, nullptr, 0, nullptr);
        vkEndCommandBuffer(cmd);
        // Run the denoiser-output copy on the compute queue when the async
        // path is available, so the graphics queue stays free (see
        // submitDenoiseCopy()).
        this->submitDenoiseCopy(cmd);
        this->denoiseResultReady = TRUE;

        if (COIN_VULKAN_ENV_FLAG("FC_VULKAN_BLACK_DEBUG")) {
          float * dbg = static_cast<float *>(this->denoiseStagingPtr);
          float * albR = dbg + stride / 4;
          float * nrmR = dbg + 2 * stride / 4;
          const int mid = ((h / 2) * w + w / 2) * 4;
          // scan a horizontal strip at mid-height for lit (alpha>0) color runs
          int litPixels = 0;
          for (int x = 0; x < w; ++x) {
            if (dbg[((h / 2) * w + x) * 4 + 3] > 0.0f) { litPixels++; }
          }
          // vertical extent of lit pixels
          int litTop = -1, litBottom = -1;
          for (int y = 0; y < h; ++y) {
            int rowLit = 0;
            for (int x = 0; x < w; x += 8) {
              if (dbg[(y * w + x) * 4 + 3] > 0.0f) { rowLit++; }
            }
            if (rowLit > 0) { if (litTop < 0) litTop = y; litBottom = y; }
          }
          fprintf(stderr,
                  "[BLACKOIDN] %ux%u accumMid=(%.3f,%.3f,%.3f,%.1f) "
                  "albedoMid=(%.3f,%.3f,%.3f,%.1f) litRow=%d/%u litTop=%d litBottom=%d outMid=(%.3f,%.3f,%.3f,%.1f)\n",
                  w, h,
                  dbg[mid], dbg[mid + 1], dbg[mid + 2], dbg[mid + 3],
                  albR[mid], albR[mid + 1], albR[mid + 2], albR[mid + 3],
                  litPixels, w, litTop, litBottom,
                  (dbg + 4 * stride / 4)[mid],
                  (dbg + 4 * stride / 4)[mid + 1],
                  (dbg + 4 * stride / 4)[mid + 2],
                  (dbg + 4 * stride / 4)[mid + 3]);
        }

        this->convergeAfterDenoise();
      }
      else {
        this->denoiseResultReady = FALSE;
        this->convergeAfterDenoise();
      }
      if (getenv("FC_VULKAN_PT_DENOISE_TIMING")) {
        fprintf(stderr, "[DENOISE] OIDN async worker published (%ux%u)\n",
                w, h);
      }
    }
    else {
      this->denoiseResultReady = FALSE;
      this->convergeAfterDenoise();
    }
    return;
  }
  if (this->oidnWorkerRunning) {
    // Worker still in flight: keep the run alive (do not accumulate further or
    // converge) so the refresh loop keeps pulling frames and the present shows
    // the fresh in-shader edge-stopped mean until the result is published.
    // The readback was already recorded once; the gating in
    // recordTraceAndPresent (!oidnWorkerRunning) prevents a new readback from
    // overwriting the staging block the worker is reading.
    return;
  }
#endif

  // Denoise-at-target: the denoiser runs exactly once, when the accumulation
  // reaches the target sample count (ptDenoisePending, set by the state
  // machine in updatePathTracingState).  Re-denoising a changing partial
  // image every accumulating frame is what churns the presented output and
  // reads as "keeps getting grainy after I move the camera."  While
  // accumulating toward the target the present shader shows the in-shader
  // edge-stopped running mean, which is monotonic and clean; the denoised
  // result is published once, on the final accumulated frame, and kept for
  // the idle view.
  if (!this->ptDenoisePending) {
    return;
  }
  // Not accumulating means the target was never reached for this run (e.g. a
  // move reset it); clear the latch so it does not fire against stale data.
  if (!this->ptAccumulating && !this->ptConverged) {
    this->ptDenoisePending = FALSE;
    this->denoiseResultReady = FALSE;
    return;
  }
  // Don't publish the denoiser output for a barely-accumulated frame: the
  // denoiser is trained on partially converged images, so a 1-2 sample frame
  // comes out blurred/junk.  Below the threshold the present shader shows the
  // raw / in-shader edge-stopped accumulation instead.
  if (this->denoiseMinSamples > 0 &&
      this->ptFrameIndex + 1 < this->denoiseMinSamples) {
    this->ptDenoisePending = FALSE;
    this->denoiseResultReady = FALSE;
    return;
  }

#if COIN_BUILD_RTX_DENOISER
  // GPU-side path: the G-buffers were copied device-to-device into the CUDA
  // interop images; normalize the accum sum -> average with the embedded CUDA
  // kernel, run OptiX on the real device pointers, then blit the device output
  // image back to the present's denoisedBuffer.  No host round-trip.
  if (this->denoiseKind == DenoiseRtx && this->rtxInteropReady) {
    const uint32_t w = this->denoiseWidth;
    const uint32_t h = this->denoiseHeight;
    const double t0 = std::chrono::duration<double>(
      std::chrono::steady_clock::now().time_since_epoch()).count();
    const bool wantCudaSignal = this->rtxInteropSemaphoresReady &&
                                this->denoisedBuffer != VK_NULL_HANDLE;
    if (!this->updateRtxDenoise(w, h, wantCudaSignal)) {
      if (this->rtxCudaSignalPending) {
        this->consumeVulkanSemaphore(this->rtxCudaToVkSem);
        this->rtxCudaSignalPending = false;
      }
      this->denoiseResultReady = FALSE;
      this->convergeAfterDenoise();
      return;
    }
    // Copy the CUDA output image (interop device buffer) back to the
    // device-local denoisedBuffer bound at present binding 5.
    VkCommandBuffer cmd = this->beginTransientCommandBuffer();
    if (cmd == VK_NULL_HANDLE) {
      if (this->rtxCudaSignalPending) {
        this->consumeVulkanSemaphore(this->rtxCudaToVkSem);
        this->rtxCudaSignalPending = false;
      }
      vkQueueWaitIdle(this->queue);
      this->denoiseResultReady = FALSE;
      this->convergeAfterDenoise();
      return;
    }
    VkMemoryBarrier hostBar {};
    hostBar.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    hostBar.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    hostBar.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                         VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 1, &hostBar, 0,
                         nullptr, 0, nullptr);
    const VkDeviceSize stride = static_cast<VkDeviceSize>(w) * h * 16;
    VkBufferCopy cOut {0, 0, stride};
    vkCmdCopyBuffer(cmd, this->rtxOutputVk, this->denoisedBuffer, 1, &cOut);
    VkMemoryBarrier outBar {};
    outBar.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    outBar.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    outBar.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 1,
                         &outBar, 0, nullptr, 0, nullptr);
    vkEndCommandBuffer(cmd);
    VkSubmitInfo si {};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    const bool waitCudaSignal =
      this->rtxInteropSemaphoresReady && this->rtxCudaSignalPending &&
      this->rtxCudaToVkSem != VK_NULL_HANDLE;
    VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_TRANSFER_BIT;
    if (waitCudaSignal) {
      si.waitSemaphoreCount = 1;
      si.pWaitSemaphores = &this->rtxCudaToVkSem;
      si.pWaitDstStageMask = &waitStage;
    }
    const VkResult submitResult = vkQueueSubmit(this->queue, 1, &si, VK_NULL_HANDLE);
    const VkResult waitResult = submitResult == VK_SUCCESS
      ? vkQueueWaitIdle(this->queue) : VK_SUCCESS;
    if (submitResult == VK_SUCCESS && waitResult == VK_SUCCESS) {
      this->rtxCudaSignalPending = false;
      this->denoiseResultReady = TRUE;
      this->convergeAfterDenoise();
    }
    else {
      if (this->rtxCudaSignalPending) {
        this->consumeVulkanSemaphore(this->rtxCudaToVkSem);
        this->rtxCudaSignalPending = false;
      }
      vkQueueWaitIdle(this->queue);
      this->denoiseResultReady = FALSE;
      this->convergeAfterDenoise();
    }
    if (getenv("FC_VULKAN_PT_DENOISE_TIMING")) {
      const double t1 = std::chrono::duration<double>(
        std::chrono::steady_clock::now().time_since_epoch()).count();
      fprintf(stderr, "[DENOISE] kind=2 frame denoise took %.1f ms (%ux%u)\n",
              (t1 - t0) * 1000.0, w, h);
    }
    return;
  }
#endif

  if (this->denoiseColorBuf == VK_NULL_HANDLE || this->denoiseStagingPtr == nullptr) {
    this->denoiseResultReady = FALSE;
    this->convergeAfterDenoise();
    return;
  }
  const uint32_t w = this->denoiseWidth;
  const uint32_t h = this->denoiseHeight;
  const VkDeviceSize stride =
    static_cast<VkDeviceSize>(w) * h * 16;
  // Region pointers into the single mapping.
  float * color = static_cast<float *>(this->denoiseStagingPtr);
  float * albedo = reinterpret_cast<float *>(
    static_cast<uint8_t *>(this->denoiseStagingPtr) + stride);
  float * normal = reinterpret_cast<float *>(
    static_cast<uint8_t *>(this->denoiseStagingPtr) + 2 * stride);
  float * motion = reinterpret_cast<float *>(
    static_cast<uint8_t *>(this->denoiseStagingPtr) + 3 * stride);
  float * out = reinterpret_cast<float *>(
    static_cast<uint8_t *>(this->denoiseStagingPtr) + 4 * stride);
#if COIN_BUILD_OIDN
  if (this->denoiseKind == DenoiseOidn && this->oidnFilter) {
    // Confirm the readback request was actually issued (it is recorded on the
    // one-shot command buffer and only set when the copy is recorded).
    if (this->oidnReadbackPending) {
      // Offload the CPU-side OIDN work (normalize the accum average, run the
      // filter, stamp the validity mask) to a worker thread so the GUI thread
      // is not blocked for the tens of milliseconds OIDN's CPU device takes.
      // The staging block is HOST_VISIBLE|HOST_COHERENT, so the worker's
      // writes to the output region are visible to the device-side copy-back
      // below without an explicit flush.  The OIDN filter is owned by the
      // worker for the duration of oidnWorkerRunning; the render thread must
      // not submit to it while the worker holds it.
      if (this->oidnWorkerRunning) {
        // A worker is already in flight (a previous frame's launch).  It owns
        // the staging block: do not run another denoise, and keep the run in
        // progress so the present keeps the (fresh) in-shader edge-stopped
        // image for this frame instead of publishing a stale denoise result.
        return;
      }
      // Snapshot the dims the worker needs; the staging pointer is stable for
      // the life of the backend (mapped once in createDenoiseBackend()).
      const uint64_t pixels = static_cast<uint64_t>(w) * h;
      this->oidnReadbackPending = FALSE;
      this->oidnWorkerRunning = TRUE;
      this->oidnWorkerDone = FALSE;
      if (this->oidnWorker.joinable()) {
        this->oidnWorker.join();
      }
      this->oidnWorker = std::thread([this, color, albedo, normal, motion, out,
                                      w, h, pixels]() {
        // Normalize the accum sum -> average: the sample count sits in the
        // w channel of each color texel and is consumed here; the present
        // shader's denoised-alpha test uses the normalized w (1.0 = hit) to
        // reject denoised pixels with no primary hit.
        for (uint64_t i = 0; i < pixels; ++i) {
          float * base = color + i * 4;
          const float count = std::fabs(base[3]) > 1e-5f ? base[3] : 0.0f;
          if (count > 0.0f) {
            base[0] /= count;
            base[1] /= count;
            base[2] /= count;
            base[3] = 1.0f;
          }
          else {
            base[3] = 0.0f;
          }
        }
        // OIDN 2.x's "RT" filter rejects OIDN_FORMAT_FLOAT4 for these inputs
        // (oidnErr=3 "unsupported input image format" -> black output).  The
        // buffers are packed vec4 (w = sample count / validity) with a 16-byte
        // pixel stride; presenting the leading 3 components as FLOAT3 with the
        // same stride makes OIDN read only RGB and skip the packed alpha, so
        // the downstream float4 indexing below is still valid.
        oidnSetSharedFilterImage(this->oidnFilter, "color", color,
                                 OIDN_FORMAT_FLOAT3, w, h, 0, 16,
                                 static_cast<size_t>(w) * 16);
        oidnSetSharedFilterImage(this->oidnFilter, "albedo", albedo,
                                 OIDN_FORMAT_FLOAT3, w, h, 0, 16,
                                 static_cast<size_t>(w) * 16);
        oidnSetSharedFilterImage(this->oidnFilter, "normal", normal,
                                 OIDN_FORMAT_FLOAT3, w, h, 0, 16,
                                 static_cast<size_t>(w) * 16);
        // Motion-vector guide: the RT filter's optional 'motion' input is a
        // FLOAT2 screen-space NDC vector (current -> previous).  Our motion
        // region stores a vec4 per pixel (x,y = NDC delta, z = validity); the
        // 16-byte pixel/row stride presents the leading 2 components so OIDN
        // consumes only x,y.  The validity flag (z) is unused by OIDN 2.x's
        // motion input; a zero vector means "no motion".
        oidnSetSharedFilterImage(this->oidnFilter, "motion", motion,
                                 OIDN_FORMAT_FLOAT2, w, h, 0, 16,
                                 static_cast<size_t>(w) * 16);
        oidnSetSharedFilterImage(this->oidnFilter, "output", out,
                                 OIDN_FORMAT_FLOAT3, w, h, 0, 16,
                                 static_cast<size_t>(w) * 16);
        oidnCommitFilter(this->oidnFilter);
        oidnExecuteFilter(this->oidnFilter);
        // OIDN executes asynchronously on the device's internal threads;
        // sync so the output region and the validity stamp below are fully
        // written before the render thread reads them.
        oidnSyncDevice(this->oidnDevice);
        // OIDN can fail silently and leave the output region black (e.g. an
        // unsupported input image format).  Surface the first such failure as
        // a warning; the worker is a background thread so this cannot corrupt
        // the render state, and the in-shader edge-stopped mean still shows.
        if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
          const char * omsg = nullptr;
          const OIDNError oerr = oidnGetDeviceError(this->oidnDevice, &omsg);
          if (oerr != OIDN_ERROR_NONE) {
            fprintf(stderr, "[DENOISE] OIDN error %d: %s\n",
                    static_cast<int>(oerr), omsg ? omsg : "(null)");
          }
        }
        // Stamp the per-pixel validity mask from the (already normalized)
        // color region so the present shader can reject denoised pixels with
        // no primary hit (its DenoisedBuffer alpha test).
        for (uint64_t i = 0; i < pixels; ++i) {
          out[i * 4 + 3] = color[i * 4 + 3];
        }
        this->oidnWorkerRunning = FALSE;
        this->oidnWorkerDone = TRUE;
      });
      // The worker owns the staging block and the filter now; do not block
      // here.  The present pass for THIS frame already shows the fresh
      // in-shader edge-stopped mean; the denoised result is published on the
      // frame that observes oidnWorkerDone (copy-back + converge below).
      if (getenv("FC_VULKAN_PT_DENOISE_TIMING")) {
        fprintf(stderr, "[DENOISE] OIDN async worker launched (%ux%u)\n", w, h);
      }
      return;
    }
  }
#endif

  // (RTX denoising is handled by the interop path returned above; the host
  // OIDN path below is the only host-side denoiser.)

  // Reaching here means no denoiser actually produced a result this frame
  // (OIDN was not pending/active, or the async worker was launched above and
  // this is reached only when there was nothing to denoise).  Simulate a
  // converged-no-result transition so the run does not retry forever.
  this->denoiseResultReady = FALSE;
  this->convergeAfterDenoise();
}

void
SoRTXRenderBackend::convergeAfterDenoise()
{
  // Denoise-at-target completion: the accumulated image is final.  Stop
  // accumulating (ptAccumulating FALSE), publish the denoised result and mark
  // converged so getPathTracingRefining() goes FALSE and the viewport keeps
  // the (raw or denoised) target image without busy-looping.  ptIdleFrames
  // starts at 0 so the refresh loop requests a few frames that present the
  // just-published denoised result before it idles; the converged branch in
  // updatePathTracingState saturates it without auto-restarting.
  this->ptDenoisePending = FALSE;
  this->ptConverged = TRUE;
  this->ptAccumulating = FALSE;
  this->ptIdleFrames = 0;
  this->ptWasMoving = FALSE;
}

void
SoRTXRenderBackend::releaseDenoiseStaging()
{
#if COIN_BUILD_OIDN
  // A resize/denoiser-swap can tear the staging block down while the async
  // worker is still reading/writing it and the OIDN filter.  The worker owns
  // both for the duration of oidnWorkerRunning (and sets oidnWorkerDone when
  // it is finished), so wait on it before unmapping/freeing the host staging
  // and releasing the OIDN filter/device in destroyDenoiser().
  if (this->oidnWorker.joinable()) {
    this->oidnWorker.join();
  }
  this->oidnWorkerRunning = FALSE;
  this->oidnWorkerDone = FALSE;
#endif
  if (this->denoiseColorBuf != VK_NULL_HANDLE) {
    const VkBuffer buf = this->denoiseColorBuf;
    const VkDeviceMemory mem = this->denoiseColorMem;
    if (this->denoiseStagingPtr) {
      vkUnmapMemory(this->device, mem);
      this->denoiseStagingPtr = nullptr;
    }
    // denoiseColorBuf is the single allocation; the alias handles do not
    // own it.
    this->denoiseColorBuf = VK_NULL_HANDLE;
    this->denoiseColorMem = VK_NULL_HANDLE;
    this->denoiseAlbedoBuf = VK_NULL_HANDLE;
    this->denoiseNormalBuf = VK_NULL_HANDLE;
    this->denoiseGuideBuf = VK_NULL_HANDLE;
    this->denoiseMotionBuf = VK_NULL_HANDLE;
    this->denoiseOutBuf = VK_NULL_HANDLE;
    this->denoiseAlbedoMem = VK_NULL_HANDLE;
    this->denoiseNormalMem = VK_NULL_HANDLE;
    this->denoiseGuideMem = VK_NULL_HANDLE;
    this->denoiseMotionMem = VK_NULL_HANDLE;
    this->denoiseOutMem = VK_NULL_HANDLE;
    this->deferDestroy([this, buf, mem]() {
      if (buf != VK_NULL_HANDLE) {
        vkDestroyBuffer(this->device, buf, this->allocator);
      }
      if (mem != VK_NULL_HANDLE) {
        vkFreeMemory(this->device, mem, this->allocator);
      }
    });
  }
  // The device-local denoised output and albedo G-buffer are kept across a
  // mid-life degrade (they underpin the present shader bindings 5 and 14 and
  // are only freed by destroyDenoiser()/shutdown()), so a failed OIDN staging
  // allocation does not leave dangling descriptors.
  this->denoiseResultReady = FALSE;
}

void
SoRTXRenderBackend::destroyDenoiser()
{
  this->destroyAsyncComputeTimeline();
  this->releaseDenoiseStaging();

  // Device-local denoised output (present binding 5) and albedo G-buffer
  // (binding 14).  Free them only on full teardown, not on a mid-life degrade
  // (releaseDenoiseStaging above keeps them so the descriptor set stays
  // valid); the whole backend is going away here so it is safe.
  if (this->denoisedBuffer != VK_NULL_HANDLE) {
    const VkBuffer buf = this->denoisedBuffer;
    const VkDeviceMemory mem = this->denoisedMemory;
    this->denoisedBuffer = VK_NULL_HANDLE;
    this->denoisedMemory = VK_NULL_HANDLE;
    this->deferDestroy([this, buf, mem]() {
      if (buf != VK_NULL_HANDLE) {
        vkDestroyBuffer(this->device, buf, this->allocator);
      }
      if (mem != VK_NULL_HANDLE) {
        vkFreeMemory(this->device, mem, this->allocator);
      }
    });
  }
  if (this->albedoBuffer != VK_NULL_HANDLE) {
    const VkBuffer buf = this->albedoBuffer;
    const VkDeviceMemory mem = this->albedoMemory;
    this->albedoBuffer = VK_NULL_HANDLE;
    this->albedoMemory = VK_NULL_HANDLE;
    this->deferDestroy([this, buf, mem]() {
      if (buf != VK_NULL_HANDLE) {
        vkDestroyBuffer(this->device, buf, this->allocator);
      }
      if (mem != VK_NULL_HANDLE) {
        vkFreeMemory(this->device, mem, this->allocator);
      }
    });
  }

#if COIN_BUILD_OIDN
  if (this->oidnFilter) {
    oidnReleaseFilter(this->oidnFilter);
    this->oidnFilter = nullptr;
  }
  if (this->oidnDevice) {
    oidnReleaseDevice(this->oidnDevice);
    this->oidnDevice = nullptr;
  }
#endif

#if COIN_BUILD_RTX_DENOISER
  this->teardownRtxDenoiser();
#endif

  this->denoiserActive = false;
  this->denoiseKind = DenoiseNone;
  this->denoiseWidth = 0;
  this->denoiseHeight = 0;
  this->denoiseStagedWidth = 0;
  this->denoiseStagedHeight = 0;
  this->oidnReadbackPending = FALSE;
}

void
SoRTXRenderBackend::teardownRtxDenoiser()
{
#if COIN_BUILD_RTX_DENOISER
  // CUDA driver memory operations act on the current context, so make ours
  // current before freeing the denoiser-owned allocations.
  if (this->rtxCudaCtx) cuCtxSetCurrent(this->rtxCudaCtx);
  if (this->rtxStream) {
    cuStreamSynchronize(this->rtxStream);
  }
  if (this->rtxInteropSemaphoresReady || this->rtxVkToCudaSem != VK_NULL_HANDLE ||
      this->rtxCudaToVkSem != VK_NULL_HANDLE ||
      this->rtxVkToCudaCudaSem != nullptr ||
      this->rtxCudaToVkCudaSem != nullptr) {
    this->destroyRtxInteropSemaphore(this->rtxVkToCudaSem,
                                     this->rtxVkToCudaCudaSem, true);
    this->destroyRtxInteropSemaphore(this->rtxCudaToVkSem,
                                     this->rtxCudaToVkCudaSem, true);
  }
  this->rtxInteropSemaphoresReady = false;
  this->rtxVkToCudaSignalPending = false;
  this->rtxCudaSignalPending = false;
  if (this->rtxDenoiser) {
    optixDenoiserDestroy(this->rtxDenoiser);
    this->rtxDenoiser = nullptr;
  }
  if (this->rtxDeviceContext) {
    optixDeviceContextDestroy(this->rtxDeviceContext);
    this->rtxDeviceContext = nullptr;
  }
  if (this->rtxNormModule) {
    cuModuleUnload(this->rtxNormModule);
    this->rtxNormModule = nullptr;
    this->rtxNormKernel = nullptr;
  }
  if (this->rtxIntensity) { cuMemFree(this->rtxIntensity); this->rtxIntensity = 0; }
  if (this->rtxState) { cuMemFree(this->rtxState); this->rtxState = 0; }
  if (this->rtxScratch) { cuMemFree(this->rtxScratch); this->rtxScratch = 0; }

  // The four working images were exported from Vulkan and imported into CUDA.
  // Reverse the import (release the CUDA alias) BEFORE freeing the Vulkan
  // allocation that owns the memory.
  auto releaseInterop = [this](VkBuffer & buf, VkDeviceMemory & mem,
                               CUexternalMemory & ext) {
    if (ext) {
      cuDestroyExternalMemory(ext);
      ext = nullptr;
    }
    const VkBuffer vkBuf = buf;
    const VkDeviceMemory vkMem = mem;
    buf = VK_NULL_HANDLE;
    mem = VK_NULL_HANDLE;
    if (vkBuf != VK_NULL_HANDLE || vkMem != VK_NULL_HANDLE) {
      this->deferDestroy([this, vkBuf, vkMem]() {
        if (vkBuf != VK_NULL_HANDLE) {
          vkDestroyBuffer(this->device, vkBuf, this->allocator);
        }
        if (vkMem != VK_NULL_HANDLE) {
          vkFreeMemory(this->device, vkMem, this->allocator);
        }
      });
    }
  };
  releaseInterop(this->rtxColorVk, this->rtxColorMem, this->rtxColorExt);
  releaseInterop(this->rtxAlbedoVk, this->rtxAlbedoMem, this->rtxAlbedoExt);
  releaseInterop(this->rtxNormalVk, this->rtxNormalMem, this->rtxNormalExt);
  releaseInterop(this->rtxMotionVk, this->rtxMotionMem, this->rtxMotionExt);
  releaseInterop(this->rtxOutputVk, this->rtxOutputMem, this->rtxOutputExt);
  this->rtxColorImage = 0;
  this->rtxAlbedoImage = 0;
  this->rtxNormalImage = 0;
  this->rtxMotionImage = 0;
  this->rtxOutputImage = 0;
  this->rtxInteropReady = false;

  if (this->rtxStream) {
    cuStreamDestroy(this->rtxStream);
    this->rtxStream = nullptr;
  }
  if (this->rtxCudaCtx) {
    cuCtxDestroy(this->rtxCudaCtx);
    this->rtxCudaCtx = nullptr;
  }
#endif
}

#if COIN_BUILD_RTX_DENOISER
namespace {

void
rtxLogCallback(unsigned int level, const char * tag, const char * message,
               void * /*cbdata*/)
{
  if (getenv("FC_VULKAN_PT_DENOISER_DEBUG") || level <= 2) {
    fprintf(stderr, "[RTX-DENOISER] level=%u tag=%s: %s\n", level,
            tag ? tag : "", message ? message : "");
  }
}

} // namespace

bool
SoRTXRenderBackend::initRtxCuda()
{
  if (this->rtxDeviceContext) return true;
  if (this->rtxCudaInitFailed) return false;

  // Initialize CUDA driver once per process.
  if (cuInit(0) != CUDA_SUCCESS) {
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Enumerate devices and pick the CUDA device that corresponds to the Vulkan
  // physical device, so the external-memory interop imports memory from the
  // same GPU.  Without a match (no UUID available, or the device is absent
  // from this CUDA context) fall back to the first Turing-or-newer device --
  // the OptiX AOV denoiser needs compute capability 7.5+ (Turing) and a
  // single-slot context.  Picking device 0 unconditionally was safe only on a
  // single-GPU NVIDIA machine; on a dual-NVIDIA workstation it could bind CUDA
  // to a different GPU than the one rendering, silently corrupting the interop.
  int deviceCount = 0;
  if (cuDeviceGetCount(&deviceCount) != CUDA_SUCCESS || deviceCount <= 0) {
    this->rtxCudaInitFailed = true;
    return false;
  }

  int chosenIndex = -1;
  int fallbackIndex = -1;
  for (int i = 0; i < deviceCount; ++i) {
    CUdevice dev {};
    if (cuDeviceGet(&dev, i) != CUDA_SUCCESS) continue;
    int ccMajor = 0, ccMinor = 0;
    cuDeviceGetAttribute(&ccMajor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR,
                         dev);
    cuDeviceGetAttribute(&ccMinor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR,
                         dev);
    // Turing (7.5) is the minimum for the RTX/OptiX denoiser here; older
    // devices (Maxwell/Kepler) cannot run the AOV denoiser.
    if (ccMajor < 7 || (ccMajor == 7 && ccMinor < 5)) continue;
    if (fallbackIndex < 0) fallbackIndex = i;
    // Prefer the device whose UUID matches the Vulkan physical device.
    if (this->haveDeviceUUID) {
      CUuuid cuUuid {};
      if (cuDeviceGetUuid(&cuUuid, dev) == CUDA_SUCCESS) {
        if (std::memcmp(cuUuid.bytes, this->deviceUUID, sizeof(this->deviceUUID))
            == 0) {
          chosenIndex = i;
          break;
        }
      }
    }
  }
  if (chosenIndex < 0 && this->haveDeviceUUID) {
    // A UUID was available, but none of the CUDA devices matched it.  Do not
    // silently fall back to another GPU: importing memory into a different
    // CUDA context would bind the denoiser to the wrong physical device.
    if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
      fprintf(stderr,
              "[RTX-DENOISER] no CUDA device matches the Vulkan device UUID "
              "(count=%d)\n",
              deviceCount);
    }
    this->rtxCudaInitFailed = true;
    return false;
  }
  if (chosenIndex < 0) chosenIndex = fallbackIndex;
  if (chosenIndex < 0) {
    this->rtxCudaInitFailed = true;
    return false;
  }
  if (cuDeviceGet(&this->rtxCudaDevice, chosenIndex) != CUDA_SUCCESS) {
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Create a private CUDA context (never the current one) for the denoiser.
  // CUDA 13.x maps cuCtxCreate to cuCtxCreate_v4, which takes a
  // CUctxCreateParams* and a flags/device triple.
  if (cuCtxCreate(&this->rtxCudaCtx, nullptr, CU_CTX_SCHED_BLOCKING_SYNC,
                  this->rtxCudaDevice) != CUDA_SUCCESS) {
    this->rtxCudaInitFailed = true;
    return false;
  }

  // One stream shared by the normalize kernel, optixDenoiserComputeIntensity
  // and optixDenoiserInvoke.  Keeping them on a single stream (as NVIDIA's
  // nvpro vk_optix_denoise example does) orders the hdrIntensity write before
  // the invoke reads it.
  if (cuStreamCreate(&this->rtxStream, 0) != CUDA_SUCCESS) {
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Bind the context for the OptiX device-context creation call.
  if (cuCtxSetCurrent(this->rtxCudaCtx) != CUDA_SUCCESS) {
    this->rtxCudaInitFailed = true;
    return false;
  }

  // Initialize the OptiX host-side function table (dlopens libnvoptix.so.1).
  if (optixInit() != OPTIX_SUCCESS) {
    this->rtxCudaInitFailed = true;
    return false;
  }

  OptixDeviceContextOptions options {};
  options.logCallbackFunction = rtxLogCallback;
  options.logCallbackLevel = 2; // errors only
  if (optixDeviceContextCreate(this->rtxCudaCtx, &options,
                               &this->rtxDeviceContext) != OPTIX_SUCCESS) {
    this->rtxCudaInitFailed = true;
    return false;
  }
  return true;
}

bool
SoRTXRenderBackend::initRtxDenoiser()
{
  if (this->rtxDenoiser) return true;
  if (!this->rtxDeviceContext) return false;

  OptixDenoiserOptions dopt {};
  // AOV model with albedo + normal guides: standard for path-traced beauty.
  dopt.guideAlbedo = 1;
  dopt.guideNormal = 1;
  dopt.denoiseAlpha = OPTIX_DENOISER_ALPHA_MODE_COPY;
  if (optixDenoiserCreate(this->rtxDeviceContext, this->rtxModelKind, &dopt,
                          &this->rtxDenoiser) != OPTIX_SUCCESS) {
    return false;
  }
  if (optixDenoiserComputeMemoryResources(this->rtxDenoiser,
                                          this->denoiseWidth,
                                          this->denoiseHeight,
                                          &this->rtxSizes) != OPTIX_SUCCESS) {
    return false;
  }

  this->rtxImagePitch =
    static_cast<uint64_t>(this->denoiseWidth) * 4 * sizeof(float);
  this->rtxOutputPitchBytes = static_cast<size_t>(this->rtxImagePitch);
  this->rtxStateBytes = this->rtxSizes.stateSizeInBytes;

  // Scratch must cover the max of the set-up/invoke scratch (without overlap)
  // and the overlap-allow scratch, whichever the driver needs.
  this->rtxScratchBytes =
    std::max(this->rtxSizes.withoutOverlapScratchSizeInBytes,
             this->rtxSizes.withOverlapScratchSizeInBytes);

  const size_t imageBytes = this->rtxOutputPitchBytes * this->denoiseHeight;
  if (cuMemAlloc(&this->rtxScratch, this->rtxScratchBytes) != CUDA_SUCCESS) {
    return false;
  }
  if (cuMemAlloc(&this->rtxState, this->rtxStateBytes) != CUDA_SUCCESS) {
    return false;
  }
  if (cuMemAlloc(&this->rtxIntensity, sizeof(float)) != CUDA_SUCCESS) {
    return false;
  }

  // The four working images are exportable device-local Vulkan buffers
  // imported into CUDA, so OptiX (and the normalize kernel) read/write them
  // directly on the GPU with no host staging in between.
  VkBufferUsageFlags inUsage =
    VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT |
    VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
  VkBufferUsageFlags outUsage =
    VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
    VK_BUFFER_USAGE_TRANSFER_DST_BIT;
  if (!this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxColorVk,
                                    this->rtxColorMem, this->rtxColorExt,
                                    this->rtxColorImage) ||
      !this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxAlbedoVk,
                                    this->rtxAlbedoMem, this->rtxAlbedoExt,
                                    this->rtxAlbedoImage) ||
      !this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxNormalVk,
                                    this->rtxNormalMem, this->rtxNormalExt,
                                    this->rtxNormalImage) ||
      !this->createRtxInteropBuffer(imageBytes, inUsage, this->rtxMotionVk,
                                    this->rtxMotionMem, this->rtxMotionExt,
                                    this->rtxMotionImage) ||
      !this->createRtxInteropBuffer(imageBytes, outUsage, this->rtxOutputVk,
                                    this->rtxOutputMem, this->rtxOutputExt,
                                    this->rtxOutputImage)) {
    this->emitError("RTX denoiser: failed to create CUDA-Vulkan interop buffers");
    return false;
  }

  // Load the sum->average normalize kernel (PTX embedded below).  It runs in
  // the ongoing denoiser stream over the color image.
  if (cuModuleLoadData(&this->rtxNormModule, kCointerpNormalizePtx) !=
        CUDA_SUCCESS ||
      cuModuleGetFunction(&this->rtxNormKernel, this->rtxNormModule,
                          "cointerp_normalize") != CUDA_SUCCESS) {
    this->emitError("RTX denoiser: failed to load normalize kernel");
    return false;
  }

  this->ensureRtxInteropSemaphores();
  this->rtxInteropReady = true;
  return true;
}

bool
SoRTXRenderBackend::createRtxInteropBuffer(size_t bytes,
                                           VkBufferUsageFlags usage,
                                           VkBuffer & buffer,
                                           VkDeviceMemory & memory,
                                           CUexternalMemory & ext,
                                           CUdeviceptr & devPtr)
{
  if (!this->vkGetMemoryFdKHR) {
    this->vkGetMemoryFdKHR = loadDispatch<PFN_vkGetMemoryFdKHR>(
      vkGetDeviceProcAddr(this->device, "vkGetMemoryFdKHR"));
    if (!this->vkGetMemoryFdKHR) {
      this->emitError("RTX denoiser: vkGetMemoryFdKHR unavailable; the "
                      "VK_KHR_external_memory_fd hint was not enabled on "
                      "the device");
      return false;
    }
  }

  VkExternalMemoryBufferCreateInfo externalBufInfo {};
  externalBufInfo.sType = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO;
  externalBufInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
  VkBufferCreateInfo ci {};
  ci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  ci.pNext = &externalBufInfo;
  ci.size = bytes;
  ci.usage = usage;
  ci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(this->device, &ci, this->allocator, &buffer) != VK_SUCCESS) {
    return false;
  }

  VkPhysicalDeviceExternalBufferInfo externalQuery {};
  externalQuery.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO;
  externalQuery.flags = 0;
  externalQuery.usage = usage;
  externalQuery.handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
  VkExternalBufferProperties externalProps {};
  externalProps.sType = VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES;
  vkGetPhysicalDeviceExternalBufferProperties(this->physicalDevice,
                                              &externalQuery, &externalProps);
  const VkExternalMemoryProperties & externalMem =
    externalProps.externalMemoryProperties;
  const bool exportable =
    (externalMem.externalMemoryFeatures &
     VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT) != 0;
  const bool compatibleOpaque =
    (externalMem.compatibleHandleTypes &
     VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT) != 0;
  if (!exportable || !compatibleOpaque) {
    if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
      fprintf(stderr,
              "[RTX-DENOISER] CUDA external buffer is not exportable: "
              "features=0x%x compatible=0x%x usage=0x%x bytes=%zu\n",
              static_cast<unsigned>(externalMem.externalMemoryFeatures),
              static_cast<unsigned>(externalMem.compatibleHandleTypes),
              static_cast<unsigned>(usage), bytes);
    }
    vkDestroyBuffer(this->device, buffer, this->allocator);
    buffer = VK_NULL_HANDLE;
    return false;
  }

  const bool dedicatedOnly =
    (externalMem.externalMemoryFeatures &
     VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT) != 0;

  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(this->device, buffer, &req);

  // Request an opaque FD export so CUDA can import the same physical memory.
  VkExportMemoryAllocateInfo exportInfo {};
  exportInfo.sType = VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO;
  exportInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
  VkMemoryDedicatedAllocateInfo dedicatedInfo {};
  dedicatedInfo.sType = VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO;
  dedicatedInfo.buffer = buffer;
  dedicatedInfo.image = VK_NULL_HANDLE;
  VkMemoryAllocateFlagsInfo allocFlags {};
  allocFlags.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO;
  allocFlags.flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;
  allocFlags.pNext = dedicatedOnly ? static_cast<void *>(&dedicatedInfo)
                                   : static_cast<void *>(&exportInfo);
  dedicatedInfo.pNext = &exportInfo;
  VkMemoryAllocateInfo ai {};
  ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  ai.allocationSize = req.size;
  ai.memoryTypeIndex = this->pickMemoryType(
    req, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  ai.pNext = &allocFlags;
  if (vkAllocateMemory(this->device, &ai, this->allocator, &memory) !=
      VK_SUCCESS) {
    if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
      fprintf(stderr,
              "[RTX-DENOISER] failed to allocate external CUDA/Vulkan "
              "buffer: bytes=%zu dedicatedOnly=%d memoryType=%u\n",
              bytes, dedicatedOnly ? 1 : 0, ai.memoryTypeIndex);
    }
    vkDestroyBuffer(this->device, buffer, this->allocator);
    buffer = VK_NULL_HANDLE;
    return false;
  }
  vkBindBufferMemory(this->device, buffer, memory, 0);

  // Export an opaque FD and hand it to CUDA to map as a device pointer.
  VkMemoryGetFdInfoKHR fdInfo {};
  fdInfo.sType = VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR;
  fdInfo.memory = memory;
  fdInfo.handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
  int fd = -1;
  if (this->vkGetMemoryFdKHR(this->device, &fdInfo, &fd) != VK_SUCCESS ||
      fd < 0) {
    vkFreeMemory(this->device, memory, this->allocator);
    vkDestroyBuffer(this->device, buffer, this->allocator);
    buffer = VK_NULL_HANDLE;
    memory = VK_NULL_HANDLE;
    return false;
  }

  CUDA_EXTERNAL_MEMORY_HANDLE_DESC hdesc {};
  hdesc.type = CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD;
  hdesc.handle.fd = fd;
  hdesc.size = req.size;
  CUresult cuRes = cuImportExternalMemory(&ext, &hdesc);
  if (cuRes != CUDA_SUCCESS) {
    ::close(fd);
    vkFreeMemory(this->device, memory, this->allocator);
    vkDestroyBuffer(this->device, buffer, this->allocator);
    buffer = VK_NULL_HANDLE;
    memory = VK_NULL_HANDLE;
    ext = nullptr;
    return false;
  }
  ::close(fd); // CUDA retains a dup of the FD.

  CUDA_EXTERNAL_MEMORY_BUFFER_DESC bdesc {};
  bdesc.offset = 0;
  bdesc.size = req.size;
  bdesc.flags = 0;
  cuRes = cuExternalMemoryGetMappedBuffer(&devPtr, ext, &bdesc);
  if (cuRes != CUDA_SUCCESS) {
    cuDestroyExternalMemory(ext);
    ext = nullptr;
    vkFreeMemory(this->device, memory, this->allocator);
    vkDestroyBuffer(this->device, buffer, this->allocator);
    buffer = VK_NULL_HANDLE;
    memory = VK_NULL_HANDLE;
    return false;
  }
  return true;
}

bool
SoRTXRenderBackend::createRtxInteropSemaphore(VkSemaphore & vkSem,
                                              CUexternalSemaphore & cudaSem)
{
  vkSem = VK_NULL_HANDLE;
  cudaSem = nullptr;
  if (!this->device) {
    return false;
  }
  if (!this->vkGetSemaphoreFdKHR) {
    this->vkGetSemaphoreFdKHR = loadDispatch<PFN_vkGetSemaphoreFdKHR>(
      vkGetDeviceProcAddr(this->device, "vkGetSemaphoreFdKHR"));
    if (!this->vkGetSemaphoreFdKHR) {
      return false;
    }
  }

  VkExportSemaphoreCreateInfo exportInfo {};
  exportInfo.sType = VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO;
  exportInfo.handleTypes = VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT;
  VkSemaphoreCreateInfo ci {};
  ci.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
  ci.pNext = &exportInfo;
  ci.flags = 0;
  if (vkCreateSemaphore(this->device, &ci, this->allocator, &vkSem) !=
      VK_SUCCESS) {
    return false;
  }

  VkSemaphoreGetFdInfoKHR fdInfo {};
  fdInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_GET_FD_INFO_KHR;
  fdInfo.semaphore = vkSem;
  fdInfo.handleType = VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT;
  int fd = -1;
  if (this->vkGetSemaphoreFdKHR(this->device, &fdInfo, &fd) != VK_SUCCESS ||
      fd < 0) {
    vkDestroySemaphore(this->device, vkSem, this->allocator);
    vkSem = VK_NULL_HANDLE;
    return false;
  }

  CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC hd {};
  hd.type = CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD;
  hd.handle.fd = fd;
  hd.flags = 0;
  const CUresult cr = cuImportExternalSemaphore(&cudaSem, &hd);
  ::close(fd);
  if (cr != CUDA_SUCCESS) {
    vkDestroySemaphore(this->device, vkSem, this->allocator);
    vkSem = VK_NULL_HANDLE;
    cudaSem = nullptr;
    return false;
  }
  return true;
}

void
SoRTXRenderBackend::destroyRtxInteropSemaphore(VkSemaphore & vkSem,
                                               CUexternalSemaphore & cudaSem,
                                               bool deferVulkan)
{
  if (cudaSem) {
    cuDestroyExternalSemaphore(cudaSem);
    cudaSem = nullptr;
  }
  if (vkSem != VK_NULL_HANDLE) {
    const VkSemaphore sem = vkSem;
    vkSem = VK_NULL_HANDLE;
    if (deferVulkan) {
      this->deferDestroy([this, sem]() {
        if (sem != VK_NULL_HANDLE) {
          vkDestroySemaphore(this->device, sem, this->allocator);
        }
      });
    }
    else if (this->device != VK_NULL_HANDLE) {
      vkDestroySemaphore(this->device, sem, this->allocator);
    }
  }
}

void
SoRTXRenderBackend::ensureRtxInteropSemaphores()
{
  if (this->rtxInteropSemaphoresReady) {
    return;
  }
  if (!this->rtxCudaCtx) {
    return;
  }
  if (cuCtxSetCurrent(this->rtxCudaCtx) != CUDA_SUCCESS) {
    return;
  }

  bool ok = false;
  if (this->createRtxInteropSemaphore(this->rtxVkToCudaSem,
                                      this->rtxVkToCudaCudaSem) &&
      this->createRtxInteropSemaphore(this->rtxCudaToVkSem,
                                      this->rtxCudaToVkCudaSem)) {
    this->rtxInteropSemaphoresReady = true;
    ok = true;
  }
  if (!ok) {
    this->destroyRtxInteropSemaphore(this->rtxVkToCudaSem,
                                     this->rtxVkToCudaCudaSem, false);
    this->destroyRtxInteropSemaphore(this->rtxCudaToVkSem,
                                     this->rtxCudaToVkCudaSem, false);
    this->rtxInteropSemaphoresReady = false;
  }
  this->rtxVkToCudaSignalPending = false;
  this->rtxCudaSignalPending = false;
  if (getenv("FC_VULKAN_PT_DENOISER_DEBUG")) {
    fprintf(stderr, "[RTX-DENOISER] CUDA/Vulkan semaphores ready=%s\n",
            ok ? "yes" : "no");
  }
}

static bool
submitRtxSemaphoreBarrier(VkDevice device, VkCommandPool pool, VkQueue queue,
                          const VkAllocationCallbacks * allocator,
                          VkSemaphore semaphore, bool isSignal)
{
  (void)allocator;
  if (device == VK_NULL_HANDLE || pool == VK_NULL_HANDLE ||
      queue == VK_NULL_HANDLE || semaphore == VK_NULL_HANDLE) {
    return false;
  }

  VkCommandBufferAllocateInfo ai {};
  ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  ai.commandPool = pool;
  ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  ai.commandBufferCount = 1;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  if (vkAllocateCommandBuffers(device, &ai, &cmd) != VK_SUCCESS) {
    return false;
  }

  VkCommandBufferBeginInfo bi {};
  bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
  bool ok = vkBeginCommandBuffer(cmd, &bi) == VK_SUCCESS;
  if (ok) {
    VkMemoryBarrier noOp {};
    noOp.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    noOp.srcAccessMask = 0;
    noOp.dstAccessMask = 0;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                         VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, 0, 1, &noOp, 0,
                         nullptr, 0, nullptr);
    ok = vkEndCommandBuffer(cmd) == VK_SUCCESS;
  }
  if (ok) {
    VkSubmitInfo si {};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
    if (isSignal) {
      si.signalSemaphoreCount = 1;
      si.pSignalSemaphores = &semaphore;
    }
    else {
      si.waitSemaphoreCount = 1;
      si.pWaitSemaphores = &semaphore;
      si.pWaitDstStageMask = &waitStage;
    }
    ok = vkQueueSubmit(queue, 1, &si, VK_NULL_HANDLE) == VK_SUCCESS &&
         vkQueueWaitIdle(queue) == VK_SUCCESS;
  }
  vkFreeCommandBuffers(device, pool, 1, &cmd);
  return ok;
}

bool
SoRTXRenderBackend::signalRtxVkToCudaSemaphore()
{
  if (this->rtxVkToCudaSignalPending) {
    return true;
  }
  if (!this->rtxInteropSemaphoresReady ||
      this->rtxVkToCudaSem == VK_NULL_HANDLE) {
    return false;
  }
  if (!submitRtxSemaphoreBarrier(this->device, this->transientPool,
                                 this->queue, this->allocator,
                                 this->rtxVkToCudaSem, true)) {
    return false;
  }
  this->rtxVkToCudaSignalPending = true;
  return true;
}

bool
SoRTXRenderBackend::consumeVulkanSemaphore(VkSemaphore semaphore)
{
  return submitRtxSemaphoreBarrier(this->device, this->transientPool,
                                   this->queue, this->allocator, semaphore,
                                   false);
}

bool
SoRTXRenderBackend::updateRtxDenoise(uint32_t w, uint32_t h,
                                     bool signalCudaToVulkan)
{
  if (!this->rtxDenoiser || !this->rtxCudaCtx) return false;
  if (!this->rtxInteropReady) return false;
  this->rtxCudaSignalPending = false;

  // The color image holds the accumulated sum (rgb) with the sample count in
  // w; normalize to the average color in place before OptiX runs.
  if (cuCtxSetCurrent(this->rtxCudaCtx) != CUDA_SUCCESS) return false;

  if (this->rtxInteropSemaphoresReady) {
    if (this->signalRtxVkToCudaSemaphore()) {
      CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS waitParams {};
      waitParams.flags = 0;
      if (cuWaitExternalSemaphoresAsync(&this->rtxVkToCudaCudaSem,
                                        &waitParams, 1,
                                        this->rtxStream) == CUDA_SUCCESS) {
        this->rtxVkToCudaSignalPending = false;
      }
      else {
        cuStreamSynchronize(this->rtxStream);
        if (this->rtxVkToCudaSignalPending) {
          this->consumeVulkanSemaphore(this->rtxVkToCudaSem);
          this->rtxVkToCudaSignalPending = false;
        }
        if (this->queue != VK_NULL_HANDLE) {
          vkQueueWaitIdle(this->queue);
        }
      }
    }
    else if (this->queue != VK_NULL_HANDLE) {
      vkQueueWaitIdle(this->queue);
    }
  }
  else if (this->queue != VK_NULL_HANDLE) {
    vkQueueWaitIdle(this->queue);
  }

  {
    unsigned int n = w * h;
    const unsigned int blocks = (n + 255u) / 256u;
    void * argn[] = {&this->rtxColorImage, &n};
    if (cuLaunchKernel(this->rtxNormKernel, blocks, 1, 1, 256, 1, 1, 0,
                       this->rtxStream, argn, nullptr) != CUDA_SUCCESS) {
      return false;
    }
  }

  // Configure the input/output layers.
  OptixImage2D colorImage {};
  colorImage.data = this->rtxColorImage;
  colorImage.width = w;
  colorImage.height = h;
  colorImage.rowStrideInBytes = static_cast<unsigned int>(this->rtxImagePitch);
  colorImage.pixelStrideInBytes = 4 * sizeof(float);
  colorImage.format = OPTIX_PIXEL_FORMAT_FLOAT4;

  OptixImage2D albedoImage = colorImage;
  albedoImage.data = this->rtxAlbedoImage;
  OptixImage2D normalImage = colorImage;
  normalImage.data = this->rtxNormalImage;
  // Motion flow guide.  The flow field is a per-pixel FLOAT2 screen-space
  // NDC vector; our motion buffer is FLOAT4 (x,y = NDC delta, z = validity),
  // so a 16-byte pixel stride reads the leading two components.  This guide
  // is only consumed by the TEMPORAL model kinds; the AOV model ignores it,
  // so leaving it zero-validated against a real image is harmless.
  OptixImage2D motionImage = colorImage;
  motionImage.data = this->rtxMotionImage;
  motionImage.pixelStrideInBytes = 4 * sizeof(float);
  motionImage.format = OPTIX_PIXEL_FORMAT_FLOAT2;
  OptixImage2D outputImage = colorImage;
  outputImage.data = this->rtxOutputImage;

  OptixDenoiserGuideLayer guide {};
  guide.albedo = albedoImage;
  guide.normal = normalImage;
  guide.flow = motionImage;

  OptixDenoiserLayer layer {};
  layer.input = colorImage;
  layer.output = outputImage;
  layer.type = OPTIX_DENOISER_AOV_TYPE_BEAUTY;

  // Compute the scene exposure from the average color (auto-exposure), then
  // set up the denoiser state and invoke.  All three must run on the SAME
  // stream: optixDenoiserComputeIntensity writes hdrIntensity
  // (this->rtxIntensity) and optixDenoiserInvoke reads it via params, and a
  // cross-stream split with no ordering leaves the invoke racing the
  // intensity write (the nvpro vk_optix_denoise example uses one stream).
  OptixDenoiserParams params {};
  params.hdrIntensity = this->rtxIntensity;
  params.blendFactor = 0.0f;

  if (optixDenoiserComputeIntensity(this->rtxDenoiser, this->rtxStream,
                                    &colorImage, this->rtxIntensity,
                                    this->rtxScratch,
                                    this->rtxScratchBytes) != OPTIX_SUCCESS) {
    return false;
  }
  if (optixDenoiserSetup(this->rtxDenoiser, this->rtxStream, w, h,
                         this->rtxState, this->rtxStateBytes,
                         this->rtxScratch, this->rtxScratchBytes) !=
      OPTIX_SUCCESS) {
    return false;
  }
  if (optixDenoiserInvoke(this->rtxDenoiser, this->rtxStream, &params,
                          this->rtxState, this->rtxStateBytes, &guide, &layer,
                          1, 0, 0, this->rtxScratch,
                          this->rtxScratchBytes) != OPTIX_SUCCESS) {
    return false;
  }

  bool signalQueued = false;
  if (this->rtxInteropSemaphoresReady && signalCudaToVulkan &&
      this->rtxCudaToVkSem != VK_NULL_HANDLE) {
    CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS sig {};
    sig.flags = 0;
    signalQueued =
      cuSignalExternalSemaphoresAsync(&this->rtxCudaToVkCudaSem, &sig, 1,
                                      this->rtxStream) == CUDA_SUCCESS;
  }

  if (cuStreamSynchronize(this->rtxStream) != CUDA_SUCCESS) {
    if (signalQueued) {
      this->consumeVulkanSemaphore(this->rtxCudaToVkSem);
    }
    this->rtxCudaSignalPending = false;
    if (this->queue != VK_NULL_HANDLE) {
      vkQueueWaitIdle(this->queue);
    }
    return false;
  }

  this->rtxCudaSignalPending = signalQueued;
  if (this->queue != VK_NULL_HANDLE) {
    vkQueueWaitIdle(this->queue);
  }
  return true;
}
#endif // COIN_BUILD_RTX_DENOISER
